// The standard MIDI controllers, in order, so a CC number is an index.
// Controllers with no assigned meaning are left as "Undefined".
export const CC_NAMES = [
  "Bank Select (MSB)",
  "Modulation Wheel (MSB)",
  "Breath Controller (MSB)",
  "Undefined (MSB)",
  "Foot Pedal (MSB)",
  "Portamento Time (MSB)",
  "Data Entry (MSB)",
  "Volume (MSB)",
  "Balance (MSB)",
  "Undefined (MSB)",
  "Pan Position (MSB)",
  "Expression (MSB)",
  "Effect Control 1 (MSB)",
  "Effect Control 2 (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "General Purpose 1 (MSB)",
  "General Purpose 2 (MSB)",
  "General Purpose 3 (MSB)",
  "General Purpose 4 (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Undefined (MSB)",
  "Bank Select (LSB)",
  "Modulation Wheel (LSB)",
  "Breath Controller (LSB)",
  "Undefined (LSB)",
  "Foot Pedal (LSB)",
  "Portamento Time (LSB)",
  "Data Entry (LSB)",
  "Volume (LSB)",
  "Balance (LSB)",
  "Undefined (LSB)",
  "Pan Position (LSB)",
  "Expression (LSB)",
  "Effect Control 1 (LSB)",
  "Effect Control 2 (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "General Purpose 1 (LSB)",
  "General Purpose 2 (LSB)",
  "General Purpose 3 (LSB)",
  "General Purpose 4 (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Undefined (LSB)",
  "Hold Pedal",
  "Portamento",
  "Sostenuto Pedal",
  "Soft Pedal",
  "Legato Pedal",
  "Hold 2 Pedal",
  "Sound Variation",
  "Resonance",
  "Sound Release Time",
  "Sound Attack Time",
  "Brightness",
  "Sound Control 6",
  "Sound Control 7",
  "Sound Control 8",
  "Sound Control 9",
  "Sound Control 10",
  "General Purpose 5",
  "General Purpose 6",
  "General Purpose 7",
  "General Purpose 8",
  "Portamento Amount",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Reverb Level",
  "Tremolo Level",
  "Chorus Level",
  "Detune Level",
  "Phaser Level",
  "Data Button Increment",
  "Data Button Decrement",
  "NRPN (LSB)",
  "NRPN (MSB)",
  "RPN (LSB)",
  "RPN (MSB)",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "All Sound Off",
  "All Controllers Off",
  "Local Keyboard",
  "All Notes Off",
  "Omni Mode Off",
  "Omni Mode On",
  "Mono Operation",
  "Poly Operation",
] as const

export const ccName = (cc: number): string => CC_NAMES[cc] ?? `CC ${cc}`
