import { PatchJSON } from "./types"

// Two words picked at random, as "Velvet Heron": something to call a patch
// until it is given a name of its own. The words lean towards sound, light
// and weather, and none of them ends up rude beside another.
const ADJECTIVES = [
  "Amber",
  "Ancient",
  "Autumn",
  "Bitter",
  "Blue",
  "Bold",
  "Brass",
  "Bright",
  "Broken",
  "Calm",
  "Cedar",
  "Cobalt",
  "Copper",
  "Crimson",
  "Crystal",
  "Dappled",
  "Distant",
  "Dusky",
  "Echoing",
  "Electric",
  "Emerald",
  "Faded",
  "Fading",
  "Floating",
  "Frosted",
  "Gentle",
  "Gilded",
  "Glass",
  "Golden",
  "Hidden",
  "Hollow",
  "Hushed",
  "Iron",
  "Ivory",
  "Jade",
  "Lucid",
  "Lunar",
  "Mellow",
  "Midnight",
  "Misty",
  "Neon",
  "Nimble",
  "Northern",
  "Obsidian",
  "Pale",
  "Quiet",
  "Restless",
  "Rolling",
  "Rusty",
  "Scarlet",
  "Silent",
  "Silver",
  "Sleepy",
  "Solar",
  "Spinning",
  "Static",
  "Swift",
  "Tidal",
  "Twilight",
  "Velvet",
  "Violet",
  "Wandering",
  "Wild",
  "Winter",
] as const

const NOUNS = [
  "Anchor",
  "Aurora",
  "Beacon",
  "Bloom",
  "Canyon",
  "Cascade",
  "Chime",
  "Cinder",
  "Comet",
  "Coral",
  "Current",
  "Delta",
  "Drift",
  "Dune",
  "Echo",
  "Ember",
  "Falcon",
  "Fern",
  "Field",
  "Fjord",
  "Flare",
  "Glacier",
  "Grove",
  "Harbor",
  "Heron",
  "Horizon",
  "Lantern",
  "Lark",
  "Lotus",
  "Meadow",
  "Meteor",
  "Mirage",
  "Monsoon",
  "Moth",
  "Nebula",
  "Orbit",
  "Otter",
  "Pulse",
  "Quartz",
  "Raven",
  "Reef",
  "Ripple",
  "River",
  "Rook",
  "Signal",
  "Sparrow",
  "Spire",
  "Summit",
  "Swell",
  "Tempest",
  "Thicket",
  "Thunder",
  "Tide",
  "Valley",
  "Vapor",
  "Vessel",
  "Willow",
  "Wren",
] as const

const pick = <T>(words: readonly T[], random: () => number): T =>
  words[Math.floor(random() * words.length) % words.length]

/** A name for a patch, as "Velvet Heron". */
export const generatePatchName = (random: () => number = Math.random) =>
  `${pick(ADJECTIVES, random)} ${pick(NOUNS, random)}`

/**
 * The patch as it is if it has a name, or else named `fallback` — its
 * file's, say — or, with none of those, a name made up for it.
 */
export const withPatchName = (patch: PatchJSON, fallback = ""): PatchJSON =>
  patch.name.trim() !== ""
    ? patch
    : {
        ...patch,
        name: fallback.trim() !== "" ? fallback.trim() : generatePatchName(),
      }
