// The English strings: the app's own, and the keys every other language
// translates. A string may hold {placeholders} and plural choices; see
// format.ts.
const en = {
  "sequencer-preview-pending": "Preparing preview…",
  "sequencer-preview-unavailable": "Preview unavailable",
  "sequencer-panel": "Sequencer",
  "sequencer-grid": "Grid",
  "sequencer-step-editor": "Step Editor",
  "sequencer-voices": "Voices",
  "sequencer-settings-panes": "Settings panes",
  "sequencer-action-hold": "Hold",
  "sequencer-action-sync": "Sync",
  "sequencer-action-flip": "Flip",
  "sequencer-action-transpose": "Transpose",
  "sequencer-action-hold-hint":
    "Keeps the sequencer on its step while the voices play on (H)",
  "sequencer-action-sync-hint":
    "Plays the selected voice at the sequencer's pace, a note each step (Y)",
  "sequencer-action-flip-hint":
    "Swaps the grid's rows and columns, from the next step on (F)",
  "sequencer-action-transpose-hint":
    "Transposes new notes by the sequencer's Transpose setting (T)",
  "sequencer-action-latch-hint":
    "A click turns an action on until it is clicked again, rather than only while it is held",
  "sequencer-actions": "Actions",
  "sequencer-action-off": "Off",
  "sequencer-action-on": "On",
  "sequencer-play": "Play",
  "sequencer-pause": "Pause",
  "sequencer-stop": "Stop",
  "sequencer-bpm-value": "{bpm} BPM",
  "sequencer-step-number": "Step {step}",
  "sequencer-steps-count": "{count, plural, one {# step} other {# steps}}",
  "sequencer-ccs-count": "{count, plural, one {# CC} other {# CCs}}",
  "sequencer-record": "Record",
  "sequencer-file": "File",
  "sequencer-edit": "Edit",
  "sequencer-file-new": "New",
  "sequencer-file-open": "Open…",
  "sequencer-file-save": "Save",
  "sequencer-file-save-as": "Save as…",
  "sequencer-file-export-midi": "Export MIDI…",
  "sequencer-file-import-midi": "Import MIDI…",
  "sequencer-file-render-audio": "Render Audio…",
  "sequencer-file-recent-patches": "Recent patches",
  "sequencer-file-recent-midi": "Recent MIDI imports",
  "sequencer-confirm-discard": "This patch has unsaved changes. Discard them?",
  "sequencer-recent-gone":
    "Couldn't find {name}. It may have been moved or deleted.",
  "sequencer-failed-open-recent": "Couldn't open {name}.",
  "sequencer-failed-open-file": "Couldn't open a file.",
  "sequencer-failed-read-patch": "Couldn't open that file.",
  "sequencer-failed-save-patch": "Couldn't save the patch.",
  "sequencer-failed-export-patterns": "Couldn't export the patterns.",
  "sequencer-failed-import-patterns": "Couldn't import patterns.",
  "sequencer-failed-read-patterns": "Couldn't import those patterns.",
  "sequencer-failed-export-midi": "Couldn't export MIDI.",
  "sequencer-failed-export-step": "Couldn't export the step as MIDI.",
  "sequencer-failed-open-midi": "Couldn't open the MIDI file.",
  "sequencer-failed-read-midi": "Couldn't read the MIDI file.",
  "sequencer-failed-read-midi-file": "Couldn't import that file.",
  "sequencer-failed-save-audio": "Couldn't save the audio.",
  "sequencer-failed-load-soundfont": "Couldn't load the SoundFont.",
  "sequencer-failed-render-audio": "Couldn't render the audio.",
  "sequencer-error-read-denied": "The browser wasn't allowed to read it.",
  "sequencer-import-midi": "Import MIDI: {name}",
  "sequencer-import-action": "Import",
  "sequencer-import-nothing": "Nothing to import from this stretch",
  "sequencer-import-fills": "Fills steps {first}–{last} of {total}",
  "sequencer-import-round": "round {times}×",
  "sequencer-import-dealt":
    "{steps, plural, one {# step} other {# steps}} of {notes, plural, one {# note} other {# notes}}",
  "sequencer-import-dont-fit":
    "{count, plural, one {# note doesn't fit} other {# notes don't fit}}",
  "sequencer-import-preview": "Preview: {name}",
  "sequencer-import-loading": "Reading {name}…",
  "sequencer-import-filter": "MIDI filter",
  "sequencer-import-options": "Options",
  "sequencer-import-tracks-chosen":
    "{chosen} of {count, plural, one {# track} other {# tracks}}",
  "sequencer-import-notes-a-step":
    "{count, plural, one {# note a step} other {# notes a step}}",
  "sequencer-import-from": "from step {step}",
  "sequencer-import-looping": "looping",
  "sequencer-import-filter-hint":
    "Starts from the MIDI input's filter in Settings; changes here are for this import only. Notes it keeps out show gray and aren't imported.",
  "sequencer-import-filtered": "filtered out",
  "sequencer-import-all-channels": "all channels",
  "sequencer-import-no-channels": "no channels",
  "sequencer-import-all-notes": "all notes",
  "sequencer-import-snap": "Snap",
  "sequencer-import-snap-bar": "Bar",
  "sequencer-import-snap-beat": "Beat",
  "sequencer-import-snap-off": "Off",
  "sequencer-import-start": "Import start",
  "sequencer-import-end": "Import end",
  "sequencer-import-bar": "bar {bar}",
  "sequencer-import-parts": "Tracks",
  "sequencer-import-no-notes": "This file has no notes.",
  "sequencer-import-track": "Track {track}",
  "sequencer-import-notes": "{count, plural, one {# note} other {# notes}}",
  "sequencer-import-notes-per-step": "Notes a step",
  "sequencer-import-drums": "drums",
  "sequencer-import-no-ccs": "This file sends no CCs.",
  "sequencer-import-changes":
    "{count, plural, one {# change} other {# changes}}",
  "sequencer-import-steps": "Steps",
  "sequencer-import-size-fit": "Fit",
  "sequencer-import-size-fit-hint":
    "Size the sequence to end at the last step the import fills",
  "sequencer-import-from-step": "From step",
  "sequencer-import-loop": "Loop until the grid is full",
  "sequencer-import-tempo": "Take the file's tempo",
  "sequencer-import-no-tempo": "the file doesn't say",
  "sequencer-import-hint":
    "The notes starting in the stretch go into the steps in the order they play, as many a step as chosen — which becomes Step notes — each key once a step. Red notes don't fit in the grid. The CCs become stepped envelopes over each step's notes. The steps filled lose what they held; one undo takes the import back.",
  "sequencer-import-settings-hint":
    "Where File → Import MIDI starts. Each import can change these for itself.",
  "sequencer-import-skip-drums": "Leave out the drum channel",
  "sequencer-import-skip-drums-note": "channel 10",
  "sequencer-import-ccs-default": "Bring in the file's CCs",
  "sequencer-import-snap-setting": "The stretch snaps to",
  "sequencer-file-export-step-midi": "Export Step MIDI…",
  "sequencer-export-step-midi": "Export MIDI: Step {step}",
  "sequencer-export-step-hint":
    "The step in the editor, as the sequence first reaches it: the notes and CCs it plays, a step long. Chance and random rules are rolled afresh.",
  "sequencer-export-settings-hint":
    "How File → Export MIDI and Export Step MIDI start, and what a step dragged out of the grid holds: drag a step onto your desktop, a folder or a DAW for its MIDI file, made with these straight away. The CCs listed are the ones this sequence sends.",
  "sequencer-export-midi": "Export MIDI",
  "sequencer-export-midi-action": "Export",
  "sequencer-export-cancel": "Cancel",
  "sequencer-export-voices": "Voices",
  "sequencer-export-ccs": "CCs",
  "sequencer-export-all-ccs": "All CCs",
  "sequencer-export-no-ccs": "This sequence sends no CCs.",
  "sequencer-export-modulation-ccs": "Modulation CCs",
  "sequencer-export-modulation-ccs-note": "the ones driving settings",
  "sequencer-export-mod": "mod {source}",
  "sequencer-export-tracks": "Tracks",
  "sequencer-export-layout-perVoice": "A track per voice",
  "sequencer-export-layout-combined": "All on one track",
  "sequencer-export-voice-off": "off",
  "sequencer-export-passes": "Passes",
  "sequencer-export-bars": "{count, plural, one {# bar} other {# bars}}",
  "sequencer-export-hint":
    "The whole sequence, as it plays from its start: each voice on its own channel with its instrument, and the CCs on theirs. Chance and random rules are rolled afresh.",
  "sequencer-render-audio": "Render Audio",
  "sequencer-render-audio-action": "Render",
  "sequencer-render-hint":
    "The whole sequence as it plays from its start, through the built-in sound: {font}. Chance and random rules are rolled afresh.",
  "sequencer-render-name": "File name",
  "sequencer-render-format": "Format",
  "sequencer-render-format-wav": "WAV",
  "sequencer-render-format-mp3": "MP3",
  "sequencer-render-sample-rate": "Sample rate",
  "sequencer-render-bit-depth": "Bit depth",
  "sequencer-render-bit-depth-16": "16-bit",
  "sequencer-render-bit-depth-24": "24-bit",
  "sequencer-render-bit-depth-32": "32-bit float",
  "sequencer-render-bitrate": "Bitrate",
  "sequencer-render-channels": "Channels",
  "sequencer-render-channels-2": "Stereo",
  "sequencer-render-channels-1": "Mono",
  "sequencer-render-tail": "Tail",
  "sequencer-render-tail-note": "left to ring out after the last step",
  "sequencer-render-normalize": "Normalize",
  "sequencer-render-normalize-note": "loudest peak at −1 dB",
  "sequencer-render-loading": "Loading the SoundFont…",
  "sequencer-render-measuring": "Measuring the level…",
  "sequencer-render-rendering": "Rendering…",
  "sequencer-render-saving": "Saving…",
  "sequencer-render-progress": "Render progress",
  "sequencer-mod-seqX": "Seq X",
  "sequencer-mod-seqY": "Seq Y",
  "sequencer-mod-phase": "Phase",
  "sequencer-mod-actionOr": "Actions",
  "sequencer-mod-voice1Random": "Voice 1 random",
  "sequencer-mod-voice2Random": "Voice 2 random",
  "sequencer-mod-voice3Random": "Voice 3 random",
  "sequencer-mod-voice4Random": "Voice 4 random",
  "sequencer-modulation": "Modulation",
  "sequencer-modulation-of": "Modulation: {target}",
  "sequencer-modulation-settings": "Modulation settings: {target}",
  "sequencer-modulation-by": "Modulated by CC {cc}",
  "sequencer-modulation-cc": "CC",
  "sequencer-modulation-cc-of": "{target} CC",
  "sequencer-modulation-from": "From",
  "sequencer-modulation-to": "To",
  "sequencer-modulation-values":
    "{count, plural, one {# value} other {# values}}",
  "sequencer-modulation-hint":
    "A step with an envelope for this CC sets this as it plays; every other step keeps the field's own value. The envelope's values are the ones between From and To.",
  "sequencer-modulation-action-hint":
    "A step with an envelope for this CC turns the action on or off, whatever its button says: Hold and Flip as the step ends, Sync as it lands, Transpose at each note. Every other step leaves it to the button.",
  "sequencer-modulation-taken": "CC {cc}: Already modulates {target}",
  "sequencer-modulation-on-steps":
    "CC {cc}: Already on {count, plural, one {# step} other {# steps}}",
  "sequencer-modulation-on":
    "{count, plural, one {On step {steps}} other {On steps {steps}}}",
  "sequencer-modulation-on-none": "Not on any step",
  "sequencer-modulation-assign": "Modulate",
  "sequencer-modulation-show": "Show on step {step}",
  "sequencer-modulation-remove": "Remove",
  "sequencer-modulation-remove-hint":
    "Stops the CC modulating this. Its envelopes stay, as CCs.",
  "sequencer-modulation-tab-transpose-fit": "Transpose fit",
  "sequencer-modulation-tab-sequencer-pace": "Seq pace",
  "sequencer-modulation-tab-sequencer-transpose": "Seq transpose",
  "sequencer-modulation-tab-sequencer-transpose-fit": "Recording fit",
  "sequencer-modulation-modulates": "Modulates {target}",
  "sequencer-undo": "Undo",
  "sequencer-redo": "Redo",
  "sequencer-size": "Size",
  "sequencer-pace": "Pace",
  "sequencer-direction": "Direction",
  "sequencer-direction-fwd": "Forwards",
  "sequencer-direction-bwd": "Backwards",
  "sequencer-direction-fwdbwd": "Fwd / Bwd",
  "sequencer-direction-bwdfwd": "Bwd / Fwd",
  "sequencer-direction-random": "Random",
  "sequencer-direction-random+": "Random+",
  "sequencer-loop": "Loop",
  "sequencer-loop-recorded": "Recorded",
  "sequencer-loop-all": "All",
  "sequencer-loop-custom": "Custom",
  "sequencer-loop-end": "Loop end",
  "sequencer-sync-voices": "Sync voices",
  "sequencer-transpose-amt": "Transpose",
  "sequencer-transpose-fit": "Scale fit",
  "sequencer-record-fit": "Recording fit",
  "sequencer-max-notes": "Step notes",
  "sequencer-voice": "Voice",
  "sequencer-voice-enable": "Enable",
  "sequencer-voice-length": "Length",
  "sequencer-voice-rule": "Rule",
  "sequencer-rule-nth": "Nth",
  "sequencer-rule-lowest": "Lowest",
  "sequencer-rule-highest": "Highest",
  "sequencer-rule-random": "Random",
  "sequencer-rule-up": "Up",
  "sequencer-rule-down": "Down",
  "sequencer-rule-updown": "Up / Down",
  "sequencer-rule-downup": "Down / Up",
  "sequencer-rule-updown+": "Up / Down +",
  "sequencer-rule-downup+": "Down / Up +",
  "sequencer-rule-rise": "Rise",
  "sequencer-rule-fall": "Fall",
  "sequencer-rule-outsidein": "Outside In",
  "sequencer-rule-insideout": "Inside Out",
  "sequencer-rule-ends": "Ends",
  "sequencer-rule-shuffle": "Shuffle",
  "sequencer-rule-walk": "Walk",
  "sequencer-rule-norepeat": "No Repeat",
  "sequencer-voice-velocity": "Velocity",
  "sequencer-voice-velocity-of": "Voice {voice} velocity",
  "sequencer-voice-channel": "Channel",
  "sequencer-voice-instrument": "Instrument",
  "sequencer-voice-pattern-length": "Pattern",
  "sequencer-voice-dot": "Dot",
  "sequencer-voice-dot-of": "Voice {voice} Dot {dot}",
  "sequencer-tempo": "Tempo",
  "sequencer-step-state": "State",
  "sequencer-step-state-normal": "Normal",
  "sequencer-step-state-rest": "Rest",
  "sequencer-step-state-skip": "Skip",
  "sequencer-step-note": "Note",
  "sequencer-step-add-note": "Add note",
  "sequencer-step-remove-note": "Remove note",
  "sequencer-step-remove-note-of": "Remove note {note}",
  "sequencer-step-no-notes": "No notes. Record, or add one.",
  "sequencer-step-over-limit":
    "Notes past the limit are dimmed and stay silent.",
  "sequencer-step-trim": "Trim to limit",
  "sequencer-step-out-of-scale": "Not in the scale",
  "sequencer-step-ccs": "Velocity & CCs",
  "sequencer-step-add-cc": "Add CC",
  "sequencer-step-more-lanes": "More lanes",
  "sequencer-step-remove-cc": "Remove CC",
  "sequencer-step-remove-cc-modulation":
    "Remove CC, and the modulation of {target}",
  "sequencer-step-cc-values": "CC values",
  "sequencer-step-cc-copy": "Copy values",
  "sequencer-step-cc-paste": "Paste values",
  "sequencer-step-cc-clear": "Clear values from this step",
  "sequencer-velocity-voice-off": "off",
  "sequencer-step-cc": "CC",
  "sequencer-channel-short": "ch {channel}",
  "sequencer-envelope-not-on-step": "not on this step — draw to add",
  "sequencer-envelope": "Envelope",
  "sequencer-envelope-cc-number": "CC number",
  "sequencer-envelope-cc-channel": "CC channel",
  "sequencer-envelope-edit": "Edit",
  "sequencer-envelope-edit-tool": "Edit points",
  "sequencer-envelope-draw": "Draw",
  "sequencer-envelope-erase": "Erase",
  "sequencer-envelope-erase-hint": "Erase points: click or drag over them",
  "sequencer-envelope-grid": "Grid",
  "sequencer-envelope-point": "Point",
  "sequencer-envelope-point-value": "Value",
  "sequencer-envelope-point-value-of": "Point {point} value",
  "sequencer-envelope-point-delete": "Delete point",
  "sequencer-envelope-steps": "Steps",
  "sequencer-envelope-steps-hint":
    "Steps: each value holds until the next point, then jumps",
  "sequencer-envelope-ramps": "Ramps",
  "sequencer-envelope-ramps-hint":
    "Ramps: straight lines from each point to the next",
  "sequencer-collapse-scale":
    "Collapse scale — show only the keys the sequence plays",
  "sequencer-envelope-ruler":
    "Ruler — drag up to zoom in, down to zoom out, sideways to scroll",
  "sequencer-action-latch": "Latch",
  "sequencer-preview": "Audition step",
  "sequencer-patch-name": "Patch name",
  "sequencer-patch-name-of": "Patch name: {name}",
  "sequencer-patch-rename": "Rename the patch",
  "sequencer-jump-rule": "Rule",
  "sequencer-jump-dest": "Destination",
  "sequencer-jump-normal": "Normal",
  "sequencer-jump-pick-dest": "Pick destination",
  "sequencer-jump-pick-normal": "Pick normal",
  "sequencer-jump-add": "Jump rule",
  "sequencer-jump-remove": "Remove jump",
  "sequencer-jump-none": "None",
  "sequencer-jump-next": "Next",
  "sequencer-jump-always": "Always",
  "sequencer-jump-last": "Last",
  "sequencer-jump-not-last": "Not last",
  "sequencer-jump-hint": "Click a step in the grid to set it.",
  "sequencer-dot-collision":
    "Same note as another voice: {note} · {count, plural, one {Voice {voices}} other {Voices {voices}}}",
  "sequencer-dot-hint": "Right-click a dot for its step options.",
  "sequencer-voice-patterns": "Patterns",
  "sequencer-voice-pattern": "Voice {voice} pattern",
  "sequencer-voice-select": "Select voice {voice}",
  "sequencer-voice-mute": "Mute",
  "sequencer-voice-mute-of": "Mute Voice {voice}",
  "sequencer-voice-solo": "Solo",
  "sequencer-voice-solo-of": "Solo Voice {voice}",
  "sequencer-patterns-export": "Export patterns",
  "sequencer-patterns-import": "Import patterns",
  "sequencer-dot-articulation": "Articulation",
  "sequencer-dot-articulation-none": "None",
  "sequencer-dot-articulation-hold": "Hold",
  "sequencer-dot-articulation-tie": "Tie",
  "sequencer-dot-accent": "Accent",
  "sequencer-dot-ratchet": "Ratchet",
  "sequencer-dot-probability": "Probability",
  "sequencer-dot-condition": "Condition",
  "sequencer-dot-none": "None",
  "sequencer-dot-always": "Always",
  "sequencer-dot-last": "Last",
  "sequencer-dot-not-last": "Not last",
  "sequencer-dot-condition-always-hint":
    "Always: plays every time the pattern reaches this dot",
  "sequencer-dot-condition-2:2-hint":
    "2:2: silent on the first loop, plays on the second of every two (loops 2, 4, 6…)",
  "sequencer-dot-condition-3:3-hint":
    "3:3: silent on loops 1 and 2, plays on the third of every three (loops 3, 6, 9…)",
  "sequencer-dot-condition-4:4-hint":
    "4:4: silent on loops 1 to 3, plays on the fourth of every four (loops 4, 8, 12…)",
  "sequencer-dot-condition-1x-hint":
    "1x: plays one loop, skips the next, and so on (loops 1, 3, 5…)",
  "sequencer-dot-condition-2x-hint":
    "2x: plays two loops in a row, then skips the third (loops 1, 2, 4, 5…)",
  "sequencer-dot-condition-3x-hint":
    "3x: plays three loops in a row, then skips the fourth (loops 1, 2, 3, 5…)",
  "sequencer-dot-condition-last-hint":
    "Last: plays only if the dot just before played — not if it failed its probability, was skipped by its condition or was off",
  "sequencer-dot-condition-notLast-hint":
    "Not last: plays only if the dot just before didn't — a fallback for when it fails its probability or condition",
  "sequencer-dot-reset": "Reset dot",
  "sequencer-dot-copy": "Copy",
  "sequencer-dot-paste": "Paste",
  "sequencer-dot-shift-left": "Shift left",
  "sequencer-dot-shift-right": "Shift right",
  "sequencer-dot-swap-left": "Swap left",
  "sequencer-dot-swap-right": "Swap right",
  "sequencer-dot-insert-before": "Insert before",
  "sequencer-dot-insert-after": "Insert after",
  "sequencer-step-copy": "Copy",
  "sequencer-step-paste": "Paste",
  "sequencer-step-clear": "Clear",
  "sequencer-step-insert-before": "Insert before",
  "sequencer-step-insert-after": "Insert after",
  "sequencer-step-delete": "Delete",
  "sequencer-scale": "Scale",
  "sequencer-scale-tonic": "Scale tonic",
  "sequencer-scale-none": "Chromatic",
  "sequencer-scale-common": "Common",
  "sequencer-scale-more": "More",
  "sequencer-scale-fit": "Outside notes",
  "sequencer-scale-fit-up": "Up",
  "sequencer-scale-fit-down": "Down",
  "sequencer-scale-fit-exclude": "Exclude",
  "sequencer-scale-fit-ignore": "Ignore",
  "sequencer-scale-detected": "Detected",
  "sequencer-scale-no-notes": "Nothing to detect from",
  "sequencer-scale-detect": "Detect the scale",
  "sequencer-scale-chromatic": "Chromatic",
  "sequencer-scale-moved": "{count} moved",
  "sequencer-scale-left-out": "{count} left out",
  "sequencer-import-scale-hint":
    "Found from the notes in the chosen stretch. Notes outside the scale move up or down to fit, are left out, or are let be.",
  "sequencer-import-min-velocity": "Min velocity",
  "sequencer-import-min-velocity-note": "Softer notes are left out",
  "sequencer-import-quiet":
    "{count, plural, one {# note too soft} other {# notes too soft}}",
  "sequencer-import-note-low": "Lowest note",
  "sequencer-import-note-high": "Highest note",
  "sequencer-import-all-parts": "All",
  "sequencer-import-no-parts": "None",
  "sequencer-settings": "Settings",
  "sequencer-settings-general": "General",
  "sequencer-settings-theme": "Theme",
  "sequencer-settings-midi": "MIDI",
  "sequencer-settings-soundfont": "SoundFont",
  "sequencer-settings-export": "MIDI Export",
  "sequencer-settings-import": "MIDI Import",
  "sequencer-settings-close": "Close",
  "sequencer-language": "Language",
  "sequencer-accent-amount": "Accent amount",
  "sequencer-accent-amount-hint":
    "How far an accent moves a note's velocity, up or down.",
  "sequencer-theme-mode": "Mode",
  "sequencer-theme-mode-light": "Light",
  "sequencer-theme-mode-dark": "Dark",
  "sequencer-theme-mode-system": "System",
  "sequencer-theme-system-hint":
    "Follows your computer's light or dark setting.",
  "sequencer-theme-dark-theme": "Dark theme",
  "sequencer-theme-light-theme": "Light theme",
  "sequencer-theme-default": "Default",
  "sequencer-midi-inputs-section": "Inputs",
  "sequencer-midi-voice-outputs": "Voice outputs",
  "sequencer-midi-voice-outputs-hint":
    "A voice can also go to a port of its own, alongside the ports above.",
  "sequencer-midi-send-modulation-ccs": "Send modulation CCs",
  "sequencer-midi-modulation-ccs-hint":
    "The CCs that drive modulated settings go to every ticked output, as other step CCs do. Off, they only drive the settings.",
  "sequencer-clock": "Clock",
  "sequencer-clock-send": "Send MIDI clock",
  "sequencer-clock-hint":
    "Start, stop and 24 ticks a beat go to every ticked output, so anything listening follows midiseq's tempo.",
  "sequencer-clock-follow": "Take tempo from MIDI clock",
  "sequencer-clock-follow-hint":
    "A clock arriving at a ticked input sets the tempo. Start and stop are ignored — playing and stopping stay yours.",
  "sequencer-filter": "Input filter",
  "sequencer-filter-hint": "What the ticked inputs are allowed to send in.",
  "sequencer-filter-channels": "Channels",
  "sequencer-filter-none": "None",
  "sequencer-filter-all": "All",
  "sequencer-filter-range": "Note range",
  "sequencer-filter-low": "Lowest note",
  "sequencer-filter-high": "Highest note",
  "sequencer-filter-to": "to",
  "sequencer-filter-transpose": "Transpose",
  "sequencer-filter-semitones": "st",
  "sequencer-filter-ccs": "CC filter",
  "sequencer-midi-outputs-section": "Outputs",
  "sequencer-midi-channel": "Channel",
  "sequencer-midi-no-inputs":
    "No MIDI inputs found. Connect a keyboard, or use a loopMIDI port.",
  "sequencer-output-voice": "Voice",
  "sequencer-output-none": "None",
  "sequencer-output-disconnected": "{name} (disconnected)",
  "sequencer-builtin-synth": "Built-in synth",
  "sequencer-midi-unsupported":
    "This browser doesn't support Web MIDI. Use Chrome or Edge.",
  "sequencer-midi-error": "Couldn't access MIDI:",
  "sequencer-midi-permission-hint":
    "The browser blocked MIDI. Allow MIDI devices in this site's settings (the icon at the left of the address bar), then try again.",
  "sequencer-midi-retry": "Try again",
  "sequencer-midi-enable": "Enable MIDI",
  "sequencer-midi-enable-hint":
    "midiseq needs your permission to use MIDI devices.",
  "sequencer-no-input":
    "Nothing to record from. Tick a MIDI input in Settings.",
  "sequencer-no-output":
    "Nothing is routed. Pick an output in MIDI settings to hear this.",
  "sequencer-status-open-settings": "Open settings",
  "sequencer-synth-loading": "Starting the built-in sound…",
  "sequencer-status-dismiss": "Dismiss",
  "sequencer-synth-error": "The built-in sound didn't start:",
  "sequencer-synth-mute": "Mute the built-in synth",
  "sequencer-synth-mute-hint": "Toggle built-in synth MIDI output setting",
  "sequencer-soundfont-hint":
    "The sounds the built-in synth plays. Add your own SF2, SF3 or DLS files.",
  "sequencer-soundfont-list": "SoundFonts",
  "sequencer-soundfont-add": "Add",
  "sequencer-soundfont-adding": "Adding…",
  "sequencer-soundfont-remove": "Remove {name}",
  "sequencer-soundfont-by": "By {author}",
  "sequencer-soundfont-loading": "Loading…",
  "sequencer-soundfont-add-error": "Couldn't add it:",
  "sequencer-error-not-soundfont": "{name} isn't a SoundFont",
  "sequencer-error-soundfont-fetch": "Couldn't fetch the SoundFont ({status})",
  "sequencer-error-soundfont-gone": "That SoundFont is no longer saved",
  "sequencer-soundfont-saved-notice":
    "SoundFonts you add are saved in this browser.",
  "sequencer-soundfont-off-hint":
    "Heard once the built-in synth is chosen as an output in MIDI.",
}

export default en

/** A language's strings: one for every key the English has, and no others. */
export type Translation = Record<keyof typeof en, string>
