import type { Translation } from "./en"

// French
const fr: Translation = {
  "sequencer-preview-pending": "Préparation de l’aperçu…",
  "sequencer-preview-unavailable": "Aperçu indisponible",
  "sequencer-panel": "Séquenceur",
  "sequencer-grid": "Grille",
  "sequencer-step-editor": "Éditeur de pas",
  "sequencer-voices": "Voix",
  "sequencer-settings-panes": "Volets de réglages",
  "sequencer-action-hold": "Maintenir",
  "sequencer-action-sync": "Sync",
  "sequencer-action-flip": "Retourner",
  "sequencer-action-transpose": "Transposer",
  "sequencer-action-hold-hint":
    "Garde le séquenceur sur son pas pendant que les voix continuent de jouer (H)",
  "sequencer-action-sync-hint":
    "Joue la voix sélectionnée à la cadence du séquenceur, une note par pas (Y)",
  "sequencer-action-flip-hint":
    "Permute les lignes et les colonnes de la grille, à partir du pas suivant (F)",
  "sequencer-action-transpose-hint":
    "Transpose les nouvelles notes selon la transposition réglée dans le séquenceur (T)",
  "sequencer-action-latch-hint":
    "Un clic active une action jusqu’au clic suivant, et non plus seulement tant que le bouton est enfoncé",
  "sequencer-actions": "Actions",
  "sequencer-action-off": "Inactif",
  "sequencer-action-on": "Actif",
  "sequencer-play": "Lecture",
  "sequencer-pause": "Pause",
  "sequencer-stop": "Arrêt",
  "sequencer-bpm-value": "{bpm} BPM",
  "sequencer-step-number": "Pas {step}",
  "sequencer-steps-count": "{count} pas",
  "sequencer-ccs-count": "{count} CC",
  "sequencer-record": "Enreg.",
  "sequencer-file": "Fichier",
  "sequencer-edit": "Édition",
  "sequencer-file-new": "Nouveau",
  "sequencer-file-open": "Ouvrir…",
  "sequencer-file-save": "Enregistrer",
  "sequencer-file-save-as": "Enregistrer sous…",
  "sequencer-file-export-midi": "Exporter en MIDI…",
  "sequencer-file-import-midi": "Importer du MIDI…",
  "sequencer-file-render-audio": "Rendu audio…",
  "sequencer-file-recent-patches": "Patchs récents",
  "sequencer-file-recent-midi": "Imports MIDI récents",
  "sequencer-confirm-discard":
    "Ce patch contient des modifications non enregistrées. Les abandonner ?",
  "sequencer-recent-gone":
    "{name} est introuvable. Le fichier a peut-être été déplacé ou supprimé.",
  "sequencer-failed-open-recent": "Impossible d’ouvrir {name}.",
  "sequencer-failed-open-file": "Impossible d’ouvrir un fichier.",
  "sequencer-failed-read-patch": "Impossible d’ouvrir ce fichier.",
  "sequencer-failed-save-patch": "Impossible d’enregistrer le patch.",
  "sequencer-failed-export-patterns": "Impossible d’exporter les motifs.",
  "sequencer-failed-import-patterns": "Impossible d’importer des motifs.",
  "sequencer-failed-read-patterns": "Impossible d’importer ces motifs.",
  "sequencer-failed-export-midi": "Impossible d’exporter en MIDI.",
  "sequencer-failed-export-step": "Impossible d’exporter le pas en MIDI.",
  "sequencer-failed-open-midi": "Impossible d’ouvrir le fichier MIDI.",
  "sequencer-failed-read-midi": "Impossible de lire le fichier MIDI.",
  "sequencer-failed-read-midi-file": "Impossible d’importer ce fichier.",
  "sequencer-failed-save-audio": "Impossible d’enregistrer l’audio.",
  "sequencer-failed-load-soundfont": "Impossible de charger la SoundFont.",
  "sequencer-failed-render-audio": "Impossible d’effectuer le rendu audio.",
  "sequencer-error-read-denied":
    "Le navigateur n’a pas été autorisé à le lire.",
  "sequencer-import-midi": "Import MIDI : {name}",
  "sequencer-import-action": "Importer",
  "sequencer-import-nothing": "Rien à importer dans cette plage",
  "sequencer-import-fills": "Remplit les pas {first}–{last} sur {total}",
  "sequencer-import-round": "{times, plural, one {# tour} other {# tours}}",
  "sequencer-import-dealt":
    "{steps} pas de {notes, plural, one {# note} other {# notes}}",
  "sequencer-import-dont-fit":
    "{count, plural, one {# note ne tient pas} other {# notes ne tiennent pas}}",
  "sequencer-import-preview": "Aperçu : {name}",
  "sequencer-import-loading": "Lecture de {name}…",
  "sequencer-import-filter": "Filtre MIDI",
  "sequencer-import-options": "Options",
  "sequencer-import-tracks-chosen":
    "{chosen, plural, one {# piste} other {# pistes}} sur {count}",
  "sequencer-import-notes-a-step":
    "{count, plural, one {# note par pas} other {# notes par pas}}",
  "sequencer-import-from": "à partir du pas {step}",
  "sequencer-import-looping": "en boucle",
  "sequencer-import-filter-hint":
    "Part du filtre de l’entrée MIDI défini dans les Réglages ; les changements faits ici ne valent que pour cet import. Les notes qu’il écarte s’affichent en gris et ne sont pas importées.",
  "sequencer-import-filtered": "hors filtre",
  "sequencer-import-all-channels": "tous les canaux",
  "sequencer-import-no-channels": "aucun canal",
  "sequencer-import-all-notes": "toutes les notes",
  "sequencer-import-snap": "Magnétisme",
  "sequencer-import-snap-bar": "Mesure",
  "sequencer-import-snap-beat": "Temps",
  "sequencer-import-snap-off": "Désactivé",
  "sequencer-import-start": "Début de l’import",
  "sequencer-import-end": "Fin de l’import",
  "sequencer-import-bar": "mesure {bar}",
  "sequencer-import-parts": "Pistes",
  "sequencer-import-no-notes": "Ce fichier ne contient aucune note.",
  "sequencer-import-track": "Piste {track}",
  "sequencer-import-notes": "{count, plural, one {# note} other {# notes}}",
  "sequencer-import-notes-per-step": "Notes par pas",
  "sequencer-import-drums": "batterie",
  "sequencer-import-no-ccs": "Ce fichier n’envoie aucun CC.",
  "sequencer-import-changes":
    "{count, plural, one {# changement} other {# changements}}",
  "sequencer-import-steps": "Pas",
  "sequencer-import-size-fit": "Ajuster",
  "sequencer-import-size-fit-hint":
    "Dimensionne la séquence pour qu’elle finisse au dernier pas que l’import remplit",
  "sequencer-import-from-step": "Pas de départ",
  "sequencer-import-loop": "Boucler jusqu’à remplir la grille",
  "sequencer-import-tempo": "Reprendre le tempo du fichier",
  "sequencer-import-no-tempo": "non indiqué par le fichier",
  "sequencer-import-hint":
    "Les notes qui commencent dans la plage remplissent les pas dans l’ordre où elles sont jouées, autant par pas que choisi (ce nombre devient Notes/pas), chaque touche une seule fois par pas. Les notes en rouge ne tiennent pas dans la grille. Les CC deviennent des enveloppes en paliers sur les notes de chaque pas. Les pas remplis perdent leur contenu ; une seule annulation défait l’import.",
  "sequencer-import-settings-hint":
    "Les valeurs de départ de Fichier → Importer du MIDI. Chaque import peut les modifier pour lui seul.",
  "sequencer-import-skip-drums": "Exclure le canal de batterie",
  "sequencer-import-skip-drums-note": "canal 10",
  "sequencer-import-ccs-default": "Importer les CC du fichier",
  "sequencer-import-snap-setting": "Magnétisme de la plage",
  "sequencer-file-export-step-midi": "Exporter le pas en MIDI…",
  "sequencer-export-step-midi": "Export MIDI : pas {step}",
  "sequencer-export-step-hint":
    "Le pas ouvert dans l’éditeur, tel que la séquence l’atteint la première fois : les notes et les CC qu’il joue, sur la durée d’un pas. Les probabilités et les règles aléatoires sont tirées au sort à nouveau.",
  "sequencer-export-settings-hint":
    "Les valeurs de départ de Fichier → Exporter en MIDI et Exporter le pas en MIDI, et ce que contient un pas glissé hors de la grille : glissez un pas sur votre bureau, dans un dossier ou dans un DAW pour obtenir son fichier MIDI, créé aussitôt avec ces réglages. Les CC listés sont ceux qu’envoie cette séquence.",
  "sequencer-export-midi": "Export MIDI",
  "sequencer-export-midi-action": "Exporter",
  "sequencer-export-cancel": "Annuler",
  "sequencer-export-voices": "Voix",
  "sequencer-export-ccs": "CC",
  "sequencer-export-all-ccs": "Tous les CC",
  "sequencer-export-no-ccs": "Cette séquence n’envoie aucun CC.",
  "sequencer-export-modulation-ccs": "CC de modulation",
  "sequencer-export-modulation-ccs-note": "ceux qui pilotent des réglages",
  "sequencer-export-mod": "mod. {source}",
  "sequencer-export-tracks": "Pistes",
  "sequencer-export-layout-perVoice": "Une piste par voix",
  "sequencer-export-layout-combined": "Tout sur une piste",
  "sequencer-export-voice-off": "désactivée",
  "sequencer-export-passes": "Passages",
  "sequencer-export-bars": "{count, plural, one {# mesure} other {# mesures}}",
  "sequencer-export-hint":
    "Toute la séquence, telle qu’elle se joue depuis son début : chaque voix sur son propre canal avec son instrument, et les CC sur les leurs. Les probabilités et les règles aléatoires sont tirées au sort à nouveau.",
  "sequencer-render-audio": "Rendu audio",
  "sequencer-render-audio-action": "Lancer le rendu",
  "sequencer-render-hint":
    "Toute la séquence, telle qu’elle se joue depuis son début, par le son intégré : {font}. Les probabilités et les règles aléatoires sont tirées au sort à nouveau.",
  "sequencer-render-name": "Nom du fichier",
  "sequencer-render-format": "Format",
  "sequencer-render-format-wav": "WAV",
  "sequencer-render-format-mp3": "MP3",
  "sequencer-render-sample-rate": "Échantillonnage",
  "sequencer-render-bit-depth": "Résolution",
  "sequencer-render-bit-depth-16": "16 bits",
  "sequencer-render-bit-depth-24": "24 bits",
  "sequencer-render-bit-depth-32": "32 bits flottant",
  "sequencer-render-bitrate": "Débit",
  "sequencer-render-channels": "Canaux",
  "sequencer-render-channels-2": "Stéréo",
  "sequencer-render-channels-1": "Mono",
  "sequencer-render-tail": "Queue",
  "sequencer-render-tail-note": "pour laisser sonner après le dernier pas",
  "sequencer-render-normalize": "Normaliser",
  "sequencer-render-normalize-note": "crête maximale à −1 dB",
  "sequencer-render-loading": "Chargement de la SoundFont…",
  "sequencer-render-measuring": "Mesure du niveau…",
  "sequencer-render-rendering": "Rendu en cours…",
  "sequencer-render-saving": "Enregistrement…",
  "sequencer-render-progress": "Progression du rendu",
  "sequencer-mod-seqX": "Séq. X",
  "sequencer-mod-seqY": "Séq. Y",
  "sequencer-mod-phase": "Phase",
  "sequencer-mod-actionOr": "Actions",
  "sequencer-mod-voice1Random": "Aléatoire voix 1",
  "sequencer-mod-voice2Random": "Aléatoire voix 2",
  "sequencer-mod-voice3Random": "Aléatoire voix 3",
  "sequencer-mod-voice4Random": "Aléatoire voix 4",
  "sequencer-modulation": "Modulation",
  "sequencer-modulation-of": "Modulation : {target}",
  "sequencer-modulation-settings": "Réglages de modulation : {target}",
  "sequencer-modulation-by": "Modulé par le CC {cc}",
  "sequencer-modulation-cc": "CC",
  "sequencer-modulation-cc-of": "CC de {target}",
  "sequencer-modulation-from": "De",
  "sequencer-modulation-to": "À",
  "sequencer-modulation-values":
    "{count, plural, one {# valeur} other {# valeurs}}",
  "sequencer-modulation-hint":
    "Un pas doté d’une enveloppe pour ce CC règle ce paramètre pendant qu’il joue ; tout autre pas garde la valeur propre du champ. Les valeurs de l’enveloppe sont celles comprises entre De et À.",
  "sequencer-modulation-action-hint":
    "Un pas doté d’une enveloppe pour ce CC active ou désactive l’action, quel que soit l’état de son bouton : Maintenir et Retourner à la fin du pas, Sync à son arrivée, Transposer à chaque note. Tout autre pas s’en remet au bouton.",
  "sequencer-modulation-taken": "CC {cc} : module déjà {target}",
  "sequencer-modulation-on-steps": "CC {cc} : déjà présent sur {count} pas",
  "sequencer-modulation-on":
    "{count, plural, one {Sur le pas {steps}} other {Sur les pas {steps}}}",
  "sequencer-modulation-on-none": "Sur aucun pas",
  "sequencer-modulation-assign": "Moduler",
  "sequencer-modulation-show": "Afficher sur le pas {step}",
  "sequencer-modulation-remove": "Retirer",
  "sequencer-modulation-remove-hint":
    "Le CC cesse de moduler ce paramètre. Ses enveloppes restent, en tant que CC.",
  "sequencer-modulation-tab-transpose-fit": "Ajust. transp.",
  "sequencer-modulation-tab-sequencer-pace": "Cadence séq.",
  "sequencer-modulation-tab-sequencer-transpose": "Transp. séq.",
  "sequencer-modulation-tab-sequencer-transpose-fit": "Ajust. enreg.",
  "sequencer-modulation-modulates": "Module {target}",
  "sequencer-undo": "Annuler",
  "sequencer-redo": "Rétablir",
  "sequencer-size": "Taille",
  "sequencer-pace": "Cadence",
  "sequencer-direction": "Direction",
  "sequencer-direction-fwd": "Avant",
  "sequencer-direction-bwd": "Arrière",
  "sequencer-direction-fwdbwd": "Av. / Arr.",
  "sequencer-direction-bwdfwd": "Arr. / Av.",
  "sequencer-direction-random": "Aléatoire",
  "sequencer-direction-random+": "Aléatoire+",
  "sequencer-loop": "Boucle",
  "sequencer-loop-recorded": "Enregistrée",
  "sequencer-loop-all": "Complète",
  "sequencer-loop-custom": "Personnalisée",
  "sequencer-loop-end": "Fin de boucle",
  "sequencer-sync-voices": "Sync des voix",
  "sequencer-transpose-amt": "Transp.",
  "sequencer-transpose-fit": "Ajustement",
  "sequencer-record-fit": "Ajust. enreg.",
  "sequencer-max-notes": "Notes/pas",
  "sequencer-voice": "Voix",
  "sequencer-voice-enable": "Activer",
  "sequencer-voice-length": "Durée",
  "sequencer-voice-rule": "Règle",
  "sequencer-rule-nth": "N-ième",
  "sequencer-rule-lowest": "Plus grave",
  "sequencer-rule-highest": "Plus aiguë",
  "sequencer-rule-random": "Aléatoire",
  "sequencer-rule-up": "Montant",
  "sequencer-rule-down": "Descendant",
  "sequencer-rule-updown": "Mont. / Desc.",
  "sequencer-rule-downup": "Desc. / Mont.",
  "sequencer-rule-updown+": "Mont. / Desc. +",
  "sequencer-rule-downup+": "Desc. / Mont. +",
  "sequencer-rule-rise": "Montée",
  "sequencer-rule-fall": "Descente",
  "sequencer-rule-outsidein": "Bords → centre",
  "sequencer-rule-insideout": "Centre → bords",
  "sequencer-rule-ends": "Extrêmes",
  "sequencer-rule-shuffle": "Mélange",
  "sequencer-rule-walk": "Marche",
  "sequencer-rule-norepeat": "Sans répétition",
  "sequencer-voice-velocity": "Vélocité",
  "sequencer-voice-velocity-of": "Vélocité de la voix {voice}",
  "sequencer-voice-channel": "Canal",
  "sequencer-voice-instrument": "Instrument",
  "sequencer-voice-pattern-length": "Motif",
  "sequencer-voice-dot": "Pastille",
  "sequencer-voice-dot-of": "Voix {voice}, pastille {dot}",
  "sequencer-tempo": "Tempo",
  "sequencer-step-state": "État",
  "sequencer-step-state-normal": "Normal",
  "sequencer-step-state-rest": "Silence",
  "sequencer-step-state-skip": "Ignoré",
  "sequencer-step-note": "Note",
  "sequencer-step-add-note": "Ajouter une note",
  "sequencer-step-remove-note": "Supprimer la note",
  "sequencer-step-remove-note-of": "Supprimer la note {note}",
  "sequencer-step-no-notes": "Aucune note. Enregistrez-en, ou ajoutez-en une.",
  "sequencer-step-over-limit":
    "Les notes au-delà de la limite sont estompées et restent muettes.",
  "sequencer-step-trim": "Rogner l’excédent",
  "sequencer-step-out-of-scale": "Hors de la gamme",
  "sequencer-step-ccs": "Vélocité et CC",
  "sequencer-step-add-cc": "Ajouter un CC",
  "sequencer-step-more-lanes": "Autres couloirs",
  "sequencer-step-remove-cc": "Supprimer le CC",
  "sequencer-step-remove-cc-modulation":
    "Supprimer le CC, et la modulation de {target}",
  "sequencer-step-cc-values": "Valeurs du CC",
  "sequencer-step-cc-copy": "Copier les valeurs",
  "sequencer-step-cc-paste": "Coller les valeurs",
  "sequencer-step-cc-clear": "Effacer les valeurs de ce pas",
  "sequencer-velocity-voice-off": "désactivée",
  "sequencer-step-cc": "CC",
  "sequencer-channel-short": "can. {channel}",
  "sequencer-envelope-not-on-step":
    "absent de ce pas — dessinez pour l’ajouter",
  "sequencer-envelope": "Enveloppe",
  "sequencer-envelope-cc-number": "Numéro de CC",
  "sequencer-envelope-cc-channel": "Canal du CC",
  "sequencer-envelope-edit": "Éditer",
  "sequencer-envelope-edit-tool": "Éditer les points",
  "sequencer-envelope-draw": "Dessiner",
  "sequencer-envelope-erase": "Effacer",
  "sequencer-envelope-erase-hint":
    "Effacer des points : cliquez dessus ou faites glisser par-dessus",
  "sequencer-envelope-grid": "Grille",
  "sequencer-envelope-point": "Point",
  "sequencer-envelope-point-value": "Valeur",
  "sequencer-envelope-point-value-of": "Valeur du point {point}",
  "sequencer-envelope-point-delete": "Supprimer le point",
  "sequencer-envelope-steps": "Paliers",
  "sequencer-envelope-steps-hint":
    "Paliers : chaque valeur tient jusqu’au point suivant, puis saute",
  "sequencer-envelope-ramps": "Rampes",
  "sequencer-envelope-ramps-hint":
    "Rampes : des lignes droites d’un point au suivant",
  "sequencer-collapse-scale":
    "Replier la gamme — n’afficher que les touches jouées par la séquence",
  "sequencer-envelope-ruler":
    "Règle — glissez vers le haut pour zoomer, vers le bas pour dézoomer, sur le côté pour faire défiler",
  "sequencer-action-latch": "Verrou",
  "sequencer-preview": "Pré-écoute",
  "sequencer-patch-name": "Nom du patch",
  "sequencer-patch-name-of": "Nom du patch : {name}",
  "sequencer-patch-rename": "Renommer le patch",
  "sequencer-jump-rule": "Règle",
  "sequencer-jump-dest": "Destination",
  "sequencer-jump-normal": "Sinon",
  "sequencer-jump-pick-dest": "Choisir la destination",
  "sequencer-jump-pick-normal": "Choisir le pas de repli",
  "sequencer-jump-add": "Règle de saut",
  "sequencer-jump-remove": "Supprimer le saut",
  "sequencer-jump-none": "Aucune",
  "sequencer-jump-next": "Suivant",
  "sequencer-jump-always": "Toujours",
  "sequencer-jump-last": "Précédent",
  "sequencer-jump-not-last": "Non précédent",
  "sequencer-jump-hint": "Cliquez sur un pas de la grille pour le définir.",
  "sequencer-dot-collision":
    "{count, plural, one {Même note qu’une autre voix : {note} · Voix {voices}} other {Même note que d’autres voix : {note} · Voix {voices}}}",
  "sequencer-dot-hint":
    "Faites un clic droit sur une pastille pour ouvrir ses options.",
  "sequencer-voice-patterns": "Motifs",
  "sequencer-voice-pattern": "Motif de la voix {voice}",
  "sequencer-voice-select": "Sélectionner la voix {voice}",
  "sequencer-voice-mute": "Muet",
  "sequencer-voice-mute-of": "Voix {voice} muette",
  "sequencer-voice-solo": "Solo",
  "sequencer-voice-solo-of": "Voix {voice} en solo",
  "sequencer-patterns-export": "Exporter les motifs",
  "sequencer-patterns-import": "Importer les motifs",
  "sequencer-dot-articulation": "Articulation",
  "sequencer-dot-articulation-none": "Aucune",
  "sequencer-dot-articulation-hold": "Tenue",
  "sequencer-dot-articulation-tie": "Liaison",
  "sequencer-dot-accent": "Accent",
  "sequencer-dot-ratchet": "Ratchet",
  "sequencer-dot-probability": "Probabilité",
  "sequencer-dot-condition": "Condition",
  "sequencer-dot-none": "Aucun",
  "sequencer-dot-always": "Toujours",
  "sequencer-dot-last": "Précédent",
  "sequencer-dot-not-last": "Non précédent",
  "sequencer-dot-condition-always-hint":
    "Toujours : joue chaque fois que le motif atteint cette pastille",
  "sequencer-dot-condition-2:2-hint":
    "2:2 : muette à la première boucle, joue à la deuxième de chaque série de deux (boucles 2, 4, 6…)",
  "sequencer-dot-condition-3:3-hint":
    "3:3 : muette aux boucles 1 et 2, joue à la troisième de chaque série de trois (boucles 3, 6, 9…)",
  "sequencer-dot-condition-4:4-hint":
    "4:4 : muette aux boucles 1 à 3, joue à la quatrième de chaque série de quatre (boucles 4, 8, 12…)",
  "sequencer-dot-condition-1x-hint":
    "1x : joue une boucle, saute la suivante, et ainsi de suite (boucles 1, 3, 5…)",
  "sequencer-dot-condition-2x-hint":
    "2x : joue deux boucles d’affilée, puis saute la troisième (boucles 1, 2, 4, 5…)",
  "sequencer-dot-condition-3x-hint":
    "3x : joue trois boucles d’affilée, puis saute la quatrième (boucles 1, 2, 3, 5…)",
  "sequencer-dot-condition-last-hint":
    "Précédent : joue seulement si la pastille juste avant a joué — pas si son tirage de probabilité a échoué, si sa condition l’a sautée ou si elle était éteinte",
  "sequencer-dot-condition-notLast-hint":
    "Non précédent : joue seulement si la pastille juste avant n’a pas joué — un repli pour quand sa probabilité ou sa condition échoue",
  "sequencer-dot-reset": "Réinitialiser la pastille",
  "sequencer-dot-copy": "Copier",
  "sequencer-dot-paste": "Coller",
  "sequencer-dot-shift-left": "Décaler ←",
  "sequencer-dot-shift-right": "Décaler →",
  "sequencer-dot-swap-left": "Permuter ←",
  "sequencer-dot-swap-right": "Permuter →",
  "sequencer-dot-insert-before": "Insérer avant",
  "sequencer-dot-insert-after": "Insérer après",
  "sequencer-step-copy": "Copier",
  "sequencer-step-paste": "Coller",
  "sequencer-step-clear": "Effacer",
  "sequencer-step-insert-before": "Insérer avant",
  "sequencer-step-insert-after": "Insérer après",
  "sequencer-step-delete": "Supprimer",
  "sequencer-scale": "Gamme",
  "sequencer-scale-tonic": "Tonique de la gamme",
  "sequencer-scale-none": "Chromatique",
  "sequencer-scale-common": "Courantes",
  "sequencer-scale-more": "Autres",
  "sequencer-scale-fit": "Notes hors gamme",
  "sequencer-scale-fit-up": "Monter",
  "sequencer-scale-fit-down": "Descendre",
  "sequencer-scale-fit-exclude": "Exclure",
  "sequencer-scale-fit-ignore": "Ignorer",
  "sequencer-scale-detected": "Détectées",
  "sequencer-scale-no-notes": "Rien à analyser",
  "sequencer-scale-detect": "Détecter la gamme",
  "sequencer-scale-chromatic": "Chromatique",
  "sequencer-scale-moved":
    "{count, plural, one {# déplacée} other {# déplacées}}",
  "sequencer-scale-left-out":
    "{count, plural, one {# écartée} other {# écartées}}",
  "sequencer-import-scale-hint":
    "Déduites des notes de la plage choisie. Les notes hors gamme montent ou descendent pour s’y ajuster, sont écartées, ou laissées telles quelles.",
  "sequencer-import-min-velocity": "Vélocité min.",
  "sequencer-import-min-velocity-note": "Les notes plus douces sont écartées",
  "sequencer-import-quiet":
    "{count, plural, one {# note trop douce} other {# notes trop douces}}",
  "sequencer-import-note-low": "Note la plus grave",
  "sequencer-import-note-high": "Note la plus aiguë",
  "sequencer-import-all-parts": "Toutes",
  "sequencer-import-no-parts": "Aucune",
  "sequencer-settings": "Réglages",
  "sequencer-settings-general": "Général",
  "sequencer-settings-theme": "Thème",
  "sequencer-settings-midi": "MIDI",
  "sequencer-settings-soundfont": "SoundFont",
  "sequencer-settings-export": "Export MIDI",
  "sequencer-settings-import": "Import MIDI",
  "sequencer-settings-close": "Fermer",
  "sequencer-language": "Langue",
  "sequencer-accent-amount": "Intensité d’accent",
  "sequencer-accent-amount-hint":
    "De combien un accent modifie la vélocité d’une note, vers le haut ou vers le bas.",
  "sequencer-theme-mode": "Mode",
  "sequencer-theme-mode-light": "Clair",
  "sequencer-theme-mode-dark": "Sombre",
  "sequencer-theme-mode-system": "Système",
  "sequencer-theme-system-hint":
    "Suit le réglage clair ou sombre de votre ordinateur.",
  "sequencer-theme-dark-theme": "Thème sombre",
  "sequencer-theme-light-theme": "Thème clair",
  "sequencer-theme-default": "Par défaut",
  "sequencer-midi-inputs-section": "Entrées",
  "sequencer-midi-voice-outputs": "Sorties par voix",
  "sequencer-midi-voice-outputs-hint":
    "Une voix peut aussi sortir sur un port à elle, en plus des ports ci-dessus.",
  "sequencer-midi-send-modulation-ccs": "Envoyer les CC de modulation",
  "sequencer-midi-modulation-ccs-hint":
    "Les CC qui pilotent des réglages modulés partent vers chaque sortie cochée, comme les autres CC des pas. Désactivés, ils ne font que piloter les réglages.",
  "sequencer-clock": "Horloge",
  "sequencer-clock-send": "Envoyer l’horloge MIDI",
  "sequencer-clock-hint":
    "Le départ, l’arrêt et 24 impulsions par temps partent vers chaque sortie cochée, pour que tout appareil à l’écoute suive le tempo de midiseq.",
  "sequencer-clock-follow": "Suivre le tempo de l’horloge MIDI",
  "sequencer-clock-follow-hint":
    "Une horloge reçue sur une entrée cochée règle le tempo. Le départ et l’arrêt sont ignorés — lancer et arrêter la lecture restent entre vos mains.",
  "sequencer-filter": "Filtre d’entrée",
  "sequencer-filter-hint": "Ce que les entrées cochées ont le droit d’envoyer.",
  "sequencer-filter-channels": "Canaux",
  "sequencer-filter-none": "Aucun",
  "sequencer-filter-all": "Tous",
  "sequencer-filter-range": "Plage de notes",
  "sequencer-filter-low": "Note la plus grave",
  "sequencer-filter-high": "Note la plus aiguë",
  "sequencer-filter-to": "à",
  "sequencer-filter-transpose": "Transposition",
  "sequencer-filter-semitones": "dt",
  "sequencer-filter-ccs": "Filtre CC",
  "sequencer-midi-outputs-section": "Sorties",
  "sequencer-midi-channel": "Canal",
  "sequencer-midi-no-inputs":
    "Aucune entrée MIDI trouvée. Branchez un clavier, ou utilisez un port loopMIDI.",
  "sequencer-output-voice": "Voix",
  "sequencer-output-none": "Aucune",
  "sequencer-output-disconnected": "{name} (déconnecté)",
  "sequencer-builtin-synth": "Synthé intégré",
  "sequencer-midi-unsupported":
    "Ce navigateur ne prend pas en charge Web MIDI. Utilisez Chrome ou Edge.",
  "sequencer-midi-error": "Impossible d’accéder au MIDI :",
  "sequencer-midi-permission-hint":
    "Le navigateur a bloqué le MIDI. Autorisez les appareils MIDI dans les paramètres de ce site (l’icône à gauche de la barre d’adresse), puis réessayez.",
  "sequencer-midi-retry": "Réessayer",
  "sequencer-midi-enable": "Activer le MIDI",
  "sequencer-midi-enable-hint":
    "midiseq a besoin de votre autorisation pour utiliser les appareils MIDI.",
  "sequencer-no-input":
    "Aucune source à enregistrer. Cochez une entrée MIDI dans les Réglages.",
  "sequencer-no-output":
    "Rien n’est routé. Choisissez une sortie dans les réglages MIDI pour entendre le son.",
  "sequencer-status-open-settings": "Ouvrir les réglages",
  "sequencer-synth-loading": "Démarrage du son intégré…",
  "sequencer-status-dismiss": "Fermer",
  "sequencer-synth-error": "Le son intégré n’a pas démarré :",
  "sequencer-synth-mute": "Couper le synthé intégré",
  "sequencer-synth-mute-hint":
    "Active ou désactive le synthé intégré parmi les sorties MIDI",
  "sequencer-soundfont-hint":
    "Les sons que joue le synthé intégré. Ajoutez vos propres fichiers SF2, SF3 ou DLS.",
  "sequencer-soundfont-list": "SoundFonts",
  "sequencer-soundfont-add": "Ajouter",
  "sequencer-soundfont-adding": "Ajout…",
  "sequencer-soundfont-remove": "Supprimer {name}",
  "sequencer-soundfont-by": "Par {author}",
  "sequencer-soundfont-loading": "Chargement…",
  "sequencer-soundfont-add-error": "Impossible de l’ajouter :",
  "sequencer-error-not-soundfont": "{name} n’est pas une SoundFont",
  "sequencer-error-soundfont-fetch":
    "Impossible de récupérer la SoundFont ({status})",
  "sequencer-error-soundfont-gone": "Cette SoundFont n’est plus enregistrée",
  "sequencer-soundfont-saved-notice":
    "Les SoundFonts que vous ajoutez sont enregistrées dans ce navigateur.",
  "sequencer-soundfont-off-hint":
    "Audible une fois le synthé intégré choisi comme sortie dans l’onglet MIDI.",
}

export default fr
