import type { Translation } from "./en"

// Japanese
const ja: Translation = {
  "sequencer-preview-pending": "プレビューを準備中…",
  "sequencer-preview-unavailable": "プレビューを表示できません",
  "sequencer-panel": "シーケンサー",
  "sequencer-grid": "グリッド",
  "sequencer-step-editor": "ステップエディター",
  "sequencer-voices": "ボイス",
  "sequencer-settings-panes": "設定パネル",
  "sequencer-action-hold": "ホールド",
  "sequencer-action-sync": "同期",
  "sequencer-action-flip": "フリップ",
  "sequencer-action-transpose": "移調",
  "sequencer-action-hold-hint":
    "ボイスの演奏を続けたまま、シーケンサーを今のステップに留めます (H)",
  "sequencer-action-sync-hint":
    "選択中のボイスをシーケンサーのレートで、1 ステップに 1 音ずつ演奏します (Y)",
  "sequencer-action-flip-hint":
    "次のステップから、グリッドの行と列を入れ替えます (F)",
  "sequencer-action-transpose-hint":
    "新しいノートを、シーケンサーの「移調」設定の分だけ移調します (T)",
  "sequencer-action-latch-hint":
    "押している間だけでなく、クリックでアクションをオンにし、もう一度クリックするまでオンのままにします",
  "sequencer-actions": "アクション",
  "sequencer-action-off": "オフ",
  "sequencer-action-on": "オン",
  "sequencer-play": "再生",
  "sequencer-pause": "一時停止",
  "sequencer-stop": "停止",
  "sequencer-bpm-value": "{bpm} BPM",
  "sequencer-step-number": "ステップ {step}",
  "sequencer-steps-count": "{count} ステップ",
  "sequencer-ccs-count": "CC {count} 個",
  "sequencer-record": "録音",
  "sequencer-file": "ファイル",
  "sequencer-edit": "編集",
  "sequencer-file-new": "新規",
  "sequencer-file-open": "開く…",
  "sequencer-file-save": "保存",
  "sequencer-file-save-as": "名前を付けて保存…",
  "sequencer-file-export-midi": "MIDI を書き出す…",
  "sequencer-file-import-midi": "MIDI を読み込む…",
  "sequencer-file-render-audio": "オーディオをレンダリング…",
  "sequencer-file-recent-patches": "最近使ったパッチ",
  "sequencer-file-recent-midi": "最近読み込んだ MIDI",
  "sequencer-confirm-discard":
    "このパッチには保存されていない変更があります。破棄しますか？",
  "sequencer-recent-gone":
    "{name} が見つかりません。移動または削除された可能性があります。",
  "sequencer-failed-open-recent": "{name} を開けませんでした。",
  "sequencer-failed-open-file": "ファイルを開けませんでした。",
  "sequencer-failed-read-patch": "そのファイルを開けませんでした。",
  "sequencer-failed-save-patch": "パッチを保存できませんでした。",
  "sequencer-failed-export-patterns": "パターンを書き出せませんでした。",
  "sequencer-failed-import-patterns": "パターンを読み込めませんでした。",
  "sequencer-failed-read-patterns": "そのパターンを読み込めませんでした。",
  "sequencer-failed-export-midi": "MIDI を書き出せませんでした。",
  "sequencer-failed-export-step":
    "ステップを MIDI として書き出せませんでした。",
  "sequencer-failed-open-midi": "MIDI ファイルを開けませんでした。",
  "sequencer-failed-read-midi": "MIDI ファイルを読み取れませんでした。",
  "sequencer-failed-read-midi-file": "そのファイルを読み込めませんでした。",
  "sequencer-failed-save-audio": "オーディオを保存できませんでした。",
  "sequencer-failed-load-soundfont": "SoundFont を読み込めませんでした。",
  "sequencer-failed-render-audio": "オーディオをレンダリングできませんでした。",
  "sequencer-error-read-denied": "ブラウザーに読み取りが許可されませんでした。",
  "sequencer-import-midi": "MIDI の読み込み: {name}",
  "sequencer-import-action": "読み込む",
  "sequencer-import-nothing": "この範囲には読み込むものがありません",
  "sequencer-import-fills": "全 {total} ステップ中 {first}–{last} に配置",
  "sequencer-import-round": "{times} 周",
  "sequencer-import-dealt": "{steps} ステップ（各 {notes} ノート）",
  "sequencer-import-dont-fit": "{count} ノートが収まりません",
  "sequencer-import-preview": "プレビュー: {name}",
  "sequencer-import-loading": "{name} を読み込み中…",
  "sequencer-import-filter": "MIDI フィルター",
  "sequencer-import-options": "オプション",
  "sequencer-import-tracks-chosen": "トラック {chosen}/{count}",
  "sequencer-import-notes-a-step": "ステップ音数 {count}",
  "sequencer-import-from": "ステップ {step} から",
  "sequencer-import-looping": "ループ",
  "sequencer-import-filter-hint":
    "設定の MIDI 入力フィルターが初期値になります。ここでの変更はこの読み込みだけに適用されます。除外されるノートはグレーで表示され、読み込まれません。",
  "sequencer-import-filtered": "フィルターで除外",
  "sequencer-import-all-channels": "全チャンネル",
  "sequencer-import-no-channels": "チャンネルなし",
  "sequencer-import-all-notes": "全音域",
  "sequencer-import-snap": "スナップ",
  "sequencer-import-snap-bar": "小節",
  "sequencer-import-snap-beat": "拍",
  "sequencer-import-snap-off": "オフ",
  "sequencer-import-start": "読み込み開始",
  "sequencer-import-end": "読み込み終了",
  "sequencer-import-bar": "{bar} 小節目",
  "sequencer-import-parts": "トラック",
  "sequencer-import-no-notes": "このファイルにはノートがありません。",
  "sequencer-import-track": "トラック {track}",
  "sequencer-import-notes": "{count} ノート",
  "sequencer-import-notes-per-step": "ステップ音数",
  "sequencer-import-drums": "ドラム",
  "sequencer-import-no-ccs": "このファイルには CC がありません。",
  "sequencer-import-changes": "変化 {count} 回",
  "sequencer-import-steps": "ステップ",
  "sequencer-import-size-fit": "合わせる",
  "sequencer-import-size-fit-hint":
    "読み込みで埋まる最後のステップでシーケンスが終わるように、サイズを合わせます",
  "sequencer-import-from-step": "開始ステップ",
  "sequencer-import-loop": "グリッドが埋まるまでループ",
  "sequencer-import-tempo": "ファイルのテンポを使う",
  "sequencer-import-no-tempo": "ファイルに指定なし",
  "sequencer-import-hint":
    "範囲内で始まるノートが、演奏順に 1 ステップあたり選んだ数ずつ（この数がステップ音数になります）ステップへ入ります。同じ音高は 1 ステップに 1 回までです。赤いノートはグリッドに収まりません。CC は各ステップのノートにかかる階段状のエンベロープになります。埋めたステップの元の内容は失われますが、「元に戻す」1 回で読み込みを取り消せます。",
  "sequencer-import-settings-hint":
    "「ファイル → MIDI を読み込む」の初期設定です。読み込みごとに個別に変更できます。",
  "sequencer-import-skip-drums": "ドラムチャンネルを除外",
  "sequencer-import-skip-drums-note": "チャンネル 10",
  "sequencer-import-ccs-default": "ファイルの CC を読み込む",
  "sequencer-import-snap-setting": "範囲のスナップ",
  "sequencer-file-export-step-midi": "ステップの MIDI を書き出す…",
  "sequencer-export-step-midi": "MIDI の書き出し: ステップ {step}",
  "sequencer-export-step-hint":
    "エディターのステップを、シーケンスが最初にそこへ来たときの内容で書き出します。演奏されるノートと CC を、1 ステップ分の長さで書き出します。確率とランダムのルールは改めて抽選されます。",
  "sequencer-export-settings-hint":
    "「ファイル → MIDI を書き出す」と「ステップの MIDI を書き出す」の初期設定で、グリッドからドラッグしたステップの内容にも使われます。ステップをデスクトップやフォルダー、DAW にドラッグすると、この設定ですぐに MIDI ファイルが作られます。一覧の CC は、このシーケンスが送信するものです。",
  "sequencer-export-midi": "MIDI の書き出し",
  "sequencer-export-midi-action": "書き出す",
  "sequencer-export-cancel": "キャンセル",
  "sequencer-export-voices": "ボイス",
  "sequencer-export-ccs": "CC",
  "sequencer-export-all-ccs": "すべての CC",
  "sequencer-export-no-ccs": "このシーケンスは CC を送信しません。",
  "sequencer-export-modulation-ccs": "モジュレーション CC",
  "sequencer-export-modulation-ccs-note": "設定を動かす CC",
  "sequencer-export-mod": "MOD {source}",
  "sequencer-export-tracks": "トラック",
  "sequencer-export-layout-perVoice": "ボイスごとにトラック",
  "sequencer-export-layout-combined": "1 トラックにまとめる",
  "sequencer-export-voice-off": "オフ",
  "sequencer-export-passes": "周回数",
  "sequencer-export-bars": "{count} 小節",
  "sequencer-export-hint":
    "シーケンス全体を、最初から再生したとおりに書き出します。各ボイスはそれぞれのチャンネルと音色で、CC もそれぞれのチャンネルで書き出されます。確率とランダムのルールは改めて抽選されます。",
  "sequencer-render-audio": "オーディオのレンダリング",
  "sequencer-render-audio-action": "レンダリング",
  "sequencer-render-hint":
    "シーケンス全体を、最初から再生したとおりに内蔵音源（{font}）でレンダリングします。確率とランダムのルールは改めて抽選されます。",
  "sequencer-render-name": "ファイル名",
  "sequencer-render-format": "フォーマット",
  "sequencer-render-format-wav": "WAV",
  "sequencer-render-format-mp3": "MP3",
  "sequencer-render-sample-rate": "サンプルレート",
  "sequencer-render-bit-depth": "ビット深度",
  "sequencer-render-bit-depth-16": "16-bit",
  "sequencer-render-bit-depth-24": "24-bit",
  "sequencer-render-bit-depth-32": "32-bit 浮動小数点",
  "sequencer-render-bitrate": "ビットレート",
  "sequencer-render-channels": "チャンネル",
  "sequencer-render-channels-2": "ステレオ",
  "sequencer-render-channels-1": "モノラル",
  "sequencer-render-tail": "余韻",
  "sequencer-render-tail-note": "最後のステップの後に鳴らしておく時間",
  "sequencer-render-normalize": "ノーマライズ",
  "sequencer-render-normalize-note": "最大ピークを −1 dB に",
  "sequencer-render-loading": "SoundFont を読み込み中…",
  "sequencer-render-measuring": "レベルを測定中…",
  "sequencer-render-rendering": "レンダリング中…",
  "sequencer-render-saving": "保存中…",
  "sequencer-render-progress": "レンダリングの進行状況",
  "sequencer-mod-seqX": "Seq X",
  "sequencer-mod-seqY": "Seq Y",
  "sequencer-mod-phase": "フェーズ",
  "sequencer-mod-actionOr": "アクション",
  "sequencer-mod-voice1Random": "ボイス 1 ランダム",
  "sequencer-mod-voice2Random": "ボイス 2 ランダム",
  "sequencer-mod-voice3Random": "ボイス 3 ランダム",
  "sequencer-mod-voice4Random": "ボイス 4 ランダム",
  "sequencer-modulation": "モジュレーション",
  "sequencer-modulation-of": "モジュレーション: {target}",
  "sequencer-modulation-settings": "モジュレーション設定: {target}",
  "sequencer-modulation-by": "CC {cc} でモジュレーション中",
  "sequencer-modulation-cc": "CC",
  "sequencer-modulation-cc-of": "{target} の CC",
  "sequencer-modulation-from": "開始値",
  "sequencer-modulation-to": "終了値",
  "sequencer-modulation-values": "{count} 段階",
  "sequencer-modulation-hint":
    "この CC のエンベロープがあるステップでは、再生中にこの設定が変わります。それ以外のステップでは、この欄自体の値が使われます。エンベロープの値は「開始値」から「終了値」までの範囲に対応します。",
  "sequencer-modulation-action-hint":
    "この CC のエンベロープがあるステップでは、ボタンの状態にかかわらずアクションをオン/オフします。「ホールド」と「フリップ」はステップの終わりに、「同期」はステップの開始時に、「移調」は各ノートで切り替わります。それ以外のステップではボタンの状態に従います。",
  "sequencer-modulation-taken":
    "CC {cc}: すでに {target} をモジュレーションしています",
  "sequencer-modulation-on-steps":
    "CC {cc}: すでに {count} ステップで使われています",
  "sequencer-modulation-on": "使用ステップ: {steps}",
  "sequencer-modulation-on-none": "どのステップにもありません",
  "sequencer-modulation-assign": "割り当てる",
  "sequencer-modulation-show": "ステップ {step} に表示",
  "sequencer-modulation-remove": "解除",
  "sequencer-modulation-remove-hint":
    "この CC によるモジュレーションを解除します。エンベロープは CC として残ります。",
  "sequencer-modulation-tab-transpose-fit": "移調補正",
  "sequencer-modulation-tab-sequencer-pace": "Seq レート",
  "sequencer-modulation-tab-sequencer-transpose": "Seq 移調",
  "sequencer-modulation-tab-sequencer-transpose-fit": "録音補正",
  "sequencer-modulation-modulates": "割り当て先: {target}",
  "sequencer-undo": "元に戻す",
  "sequencer-redo": "やり直す",
  "sequencer-size": "サイズ",
  "sequencer-pace": "レート",
  "sequencer-direction": "再生方向",
  "sequencer-direction-fwd": "順方向",
  "sequencer-direction-bwd": "逆方向",
  "sequencer-direction-fwdbwd": "順 / 逆",
  "sequencer-direction-bwdfwd": "逆 / 順",
  "sequencer-direction-random": "ランダム",
  "sequencer-direction-random+": "ランダム+",
  "sequencer-loop": "ループ",
  "sequencer-loop-recorded": "録音済み",
  "sequencer-loop-all": "全体",
  "sequencer-loop-custom": "カスタム",
  "sequencer-loop-end": "ループ終端",
  "sequencer-sync-voices": "ボイス同期",
  "sequencer-transpose-amt": "移調",
  "sequencer-transpose-fit": "スケール補正",
  "sequencer-record-fit": "録音補正",
  "sequencer-max-notes": "ステップ音数",
  "sequencer-voice": "ボイス",
  "sequencer-voice-enable": "有効",
  "sequencer-voice-length": "長さ",
  "sequencer-voice-rule": "ルール",
  "sequencer-rule-nth": "N 番目",
  "sequencer-rule-lowest": "最低音",
  "sequencer-rule-highest": "最高音",
  "sequencer-rule-random": "ランダム",
  "sequencer-rule-up": "アップ",
  "sequencer-rule-down": "ダウン",
  "sequencer-rule-updown": "アップ / ダウン",
  "sequencer-rule-downup": "ダウン / アップ",
  "sequencer-rule-updown+": "アップ / ダウン +",
  "sequencer-rule-downup+": "ダウン / アップ +",
  "sequencer-rule-rise": "上昇",
  "sequencer-rule-fall": "下降",
  "sequencer-rule-outsidein": "外から内",
  "sequencer-rule-insideout": "内から外",
  "sequencer-rule-ends": "両端",
  "sequencer-rule-shuffle": "シャッフル",
  "sequencer-rule-walk": "ウォーク",
  "sequencer-rule-norepeat": "連続なし",
  "sequencer-voice-velocity": "ベロシティ",
  "sequencer-voice-velocity-of": "ボイス {voice} のベロシティ",
  "sequencer-voice-channel": "チャンネル",
  "sequencer-voice-instrument": "音色",
  "sequencer-voice-pattern-length": "パターン長",
  "sequencer-voice-dot": "ドット",
  "sequencer-voice-dot-of": "ボイス {voice} のドット {dot}",
  "sequencer-tempo": "テンポ",
  "sequencer-step-state": "状態",
  "sequencer-step-state-normal": "通常",
  "sequencer-step-state-rest": "休符",
  "sequencer-step-state-skip": "スキップ",
  "sequencer-step-note": "ノート",
  "sequencer-step-add-note": "ノートを追加",
  "sequencer-step-remove-note": "ノートを削除",
  "sequencer-step-remove-note-of": "ノート {note} を削除",
  "sequencer-step-no-notes":
    "ノートがありません。録音するか、追加してください。",
  "sequencer-step-over-limit":
    "上限を超えたノートは薄く表示され、発音しません。",
  "sequencer-step-trim": "超過分を削除",
  "sequencer-step-out-of-scale": "スケール外",
  "sequencer-step-ccs": "ベロシティと CC",
  "sequencer-step-add-cc": "CC を追加",
  "sequencer-step-more-lanes": "その他のレーン",
  "sequencer-step-remove-cc": "CC を削除",
  "sequencer-step-remove-cc-modulation":
    "CC と {target} のモジュレーションを削除",
  "sequencer-step-cc-values": "CC の値",
  "sequencer-step-cc-copy": "値をコピー",
  "sequencer-step-cc-paste": "値を貼り付け",
  "sequencer-step-cc-clear": "このステップの値を消去",
  "sequencer-velocity-voice-off": "オフ",
  "sequencer-step-cc": "CC",
  "sequencer-channel-short": "ch {channel}",
  "sequencer-envelope-not-on-step": "このステップにはなし — 描いて追加",
  "sequencer-envelope": "エンベロープ",
  "sequencer-envelope-cc-number": "CC 番号",
  "sequencer-envelope-cc-channel": "CC チャンネル",
  "sequencer-envelope-edit": "編集",
  "sequencer-envelope-edit-tool": "ポイントを編集",
  "sequencer-envelope-draw": "描画",
  "sequencer-envelope-erase": "消去",
  "sequencer-envelope-erase-hint":
    "ポイントを消去: クリックするか、ドラッグでなぞります",
  "sequencer-envelope-grid": "グリッド",
  "sequencer-envelope-point": "ポイント",
  "sequencer-envelope-point-value": "値",
  "sequencer-envelope-point-value-of": "ポイント {point} の値",
  "sequencer-envelope-point-delete": "ポイントを削除",
  "sequencer-envelope-steps": "階段",
  "sequencer-envelope-steps-hint":
    "階段: 各値を次のポイントまで保ち、そこで切り替えます",
  "sequencer-envelope-ramps": "直線",
  "sequencer-envelope-ramps-hint":
    "直線: 各ポイントから次のポイントまでを直線でつなぎます",
  "sequencer-collapse-scale":
    "スケールを折りたたむ — シーケンスで使う音だけを表示",
  "sequencer-envelope-ruler":
    "ルーラー — 上にドラッグで拡大、下で縮小、横でスクロール",
  "sequencer-action-latch": "ラッチ",
  "sequencer-preview": "ステップを試聴",
  "sequencer-patch-name": "パッチ名",
  "sequencer-patch-name-of": "パッチ名: {name}",
  "sequencer-patch-rename": "パッチ名を変更",
  "sequencer-jump-rule": "ルール",
  "sequencer-jump-dest": "ジャンプ先",
  "sequencer-jump-normal": "通常時",
  "sequencer-jump-pick-dest": "ジャンプ先を選択",
  "sequencer-jump-pick-normal": "通常時の行き先を選択",
  "sequencer-jump-add": "ジャンプルール",
  "sequencer-jump-remove": "ジャンプを削除",
  "sequencer-jump-none": "なし",
  "sequencer-jump-next": "次へ",
  "sequencer-jump-always": "常に",
  "sequencer-jump-last": "前回が成立",
  "sequencer-jump-not-last": "前回が不成立",
  "sequencer-jump-hint": "グリッドのステップをクリックして設定します。",
  "sequencer-dot-collision": "他のボイスと同じノート: {note} · ボイス {voices}",
  "sequencer-dot-hint": "ドットを右クリックすると、オプションが開きます。",
  "sequencer-voice-patterns": "パターン",
  "sequencer-voice-pattern": "ボイス {voice} のパターン",
  "sequencer-voice-select": "ボイス {voice} を選択",
  "sequencer-voice-mute": "ミュート",
  "sequencer-voice-mute-of": "ボイス {voice} をミュート",
  "sequencer-voice-solo": "ソロ",
  "sequencer-voice-solo-of": "ボイス {voice} をソロ",
  "sequencer-patterns-export": "パターンを書き出す",
  "sequencer-patterns-import": "パターンを読み込む",
  "sequencer-dot-articulation": "奏法",
  "sequencer-dot-articulation-none": "なし",
  "sequencer-dot-articulation-hold": "ホールド",
  "sequencer-dot-articulation-tie": "タイ",
  "sequencer-dot-accent": "アクセント",
  "sequencer-dot-ratchet": "ラチェット",
  "sequencer-dot-probability": "確率",
  "sequencer-dot-condition": "条件",
  "sequencer-dot-none": "なし",
  "sequencer-dot-always": "常に",
  "sequencer-dot-last": "直前が成立",
  "sequencer-dot-not-last": "直前が不成立",
  "sequencer-dot-condition-always-hint":
    "常に: パターンがこのドットに来るたびに鳴ります",
  "sequencer-dot-condition-2:2-hint":
    "2:2: 1 回目のループでは鳴らず、2 回ごとに 2 回目で鳴ります（ループ 2, 4, 6…）",
  "sequencer-dot-condition-3:3-hint":
    "3:3: ループ 1, 2 では鳴らず、3 回ごとに 3 回目で鳴ります（ループ 3, 6, 9…）",
  "sequencer-dot-condition-4:4-hint":
    "4:4: ループ 1–3 では鳴らず、4 回ごとに 4 回目で鳴ります（ループ 4, 8, 12…）",
  "sequencer-dot-condition-1x-hint":
    "1x: 1 ループ鳴らして次の 1 ループを休み、これを繰り返します（ループ 1, 3, 5…）",
  "sequencer-dot-condition-2x-hint":
    "2x: 2 ループ続けて鳴らし、3 ループ目を休みます（ループ 1, 2, 4, 5…）",
  "sequencer-dot-condition-3x-hint":
    "3x: 3 ループ続けて鳴らし、4 ループ目を休みます（ループ 1, 2, 3, 5…）",
  "sequencer-dot-condition-last-hint":
    "直前が成立: 直前のドットが鳴った場合だけ鳴ります。直前のドットが確率で外れた、条件でスキップされた、またはオフだった場合は鳴りません",
  "sequencer-dot-condition-notLast-hint":
    "直前が不成立: 直前のドットが鳴らなかった場合だけ鳴ります。直前のドットが確率や条件で外れたときの代わりに使えます",
  "sequencer-dot-reset": "ドットをリセット",
  "sequencer-dot-copy": "コピー",
  "sequencer-dot-paste": "貼り付け",
  "sequencer-dot-shift-left": "左へずらす",
  "sequencer-dot-shift-right": "右へずらす",
  "sequencer-dot-swap-left": "左と入れ替え",
  "sequencer-dot-swap-right": "右と入れ替え",
  "sequencer-dot-insert-before": "前に挿入",
  "sequencer-dot-insert-after": "後に挿入",
  "sequencer-step-copy": "コピー",
  "sequencer-step-paste": "貼り付け",
  "sequencer-step-clear": "クリア",
  "sequencer-step-insert-before": "前に挿入",
  "sequencer-step-insert-after": "後に挿入",
  "sequencer-step-delete": "削除",
  "sequencer-scale": "スケール",
  "sequencer-scale-tonic": "スケールの主音",
  "sequencer-scale-none": "クロマチック",
  "sequencer-scale-common": "主要",
  "sequencer-scale-more": "その他",
  "sequencer-scale-fit": "スケール外のノート",
  "sequencer-scale-fit-up": "上へ",
  "sequencer-scale-fit-down": "下へ",
  "sequencer-scale-fit-exclude": "除外",
  "sequencer-scale-fit-ignore": "そのまま",
  "sequencer-scale-detected": "検出結果",
  "sequencer-scale-no-notes": "検出に使えるノートがありません",
  "sequencer-scale-detect": "スケールを検出",
  "sequencer-scale-chromatic": "クロマチック",
  "sequencer-scale-moved": "移動 {count}",
  "sequencer-scale-left-out": "除外 {count}",
  "sequencer-import-scale-hint":
    "選んだ範囲のノートから検出したスケールです。スケール外のノートは、上か下へ移動して合わせるか、除外するか、そのままにします。",
  "sequencer-import-min-velocity": "最小ベロシティ",
  "sequencer-import-min-velocity-note": "これより弱いノートは除外されます",
  "sequencer-import-quiet": "{count} ノートが弱すぎます",
  "sequencer-import-note-low": "最低音",
  "sequencer-import-note-high": "最高音",
  "sequencer-import-all-parts": "すべて",
  "sequencer-import-no-parts": "なし",
  "sequencer-settings": "設定",
  "sequencer-settings-general": "一般",
  "sequencer-settings-theme": "テーマ",
  "sequencer-settings-midi": "MIDI",
  "sequencer-settings-soundfont": "SoundFont",
  "sequencer-settings-export": "MIDI 書き出し",
  "sequencer-settings-import": "MIDI 読み込み",
  "sequencer-settings-close": "閉じる",
  "sequencer-language": "言語",
  "sequencer-accent-amount": "アクセント量",
  "sequencer-accent-amount-hint":
    "アクセントでノートのベロシティを上げ下げする量です。",
  "sequencer-theme-mode": "モード",
  "sequencer-theme-mode-light": "ライト",
  "sequencer-theme-mode-dark": "ダーク",
  "sequencer-theme-mode-system": "システム",
  "sequencer-theme-system-hint":
    "コンピューターのライト/ダーク設定に従います。",
  "sequencer-theme-dark-theme": "ダークテーマ",
  "sequencer-theme-light-theme": "ライトテーマ",
  "sequencer-theme-default": "デフォルト",
  "sequencer-midi-inputs-section": "入力",
  "sequencer-midi-voice-outputs": "ボイス出力",
  "sequencer-midi-voice-outputs-hint":
    "上のポートに加えて、ボイスごとに専用のポートへ送ることもできます。",
  "sequencer-midi-send-modulation-ccs": "モジュレーション CC を送信",
  "sequencer-midi-modulation-ccs-hint":
    "モジュレーションで設定を動かす CC も、他のステップ CC と同じく、チェックしたすべての出力に送信されます。オフにすると、設定を動かすだけになります。",
  "sequencer-clock": "クロック",
  "sequencer-clock-send": "MIDI クロックを送信",
  "sequencer-clock-hint":
    "スタート、ストップと 1 拍 24 ティックのクロックを、チェックしたすべての出力に送信します。受信側は midiseq のテンポに追従します。",
  "sequencer-clock-follow": "MIDI クロックのテンポに従う",
  "sequencer-clock-follow-hint":
    "チェックした入力に届いたクロックでテンポを設定します。スタートとストップは無視され、再生と停止はこちらで操作します。",
  "sequencer-filter": "入力フィルター",
  "sequencer-filter-hint": "チェックした入力から受け付ける内容です。",
  "sequencer-filter-channels": "チャンネル",
  "sequencer-filter-none": "なし",
  "sequencer-filter-all": "すべて",
  "sequencer-filter-range": "音域",
  "sequencer-filter-low": "最低音",
  "sequencer-filter-high": "最高音",
  "sequencer-filter-to": "〜",
  "sequencer-filter-transpose": "移調",
  "sequencer-filter-semitones": "半音",
  "sequencer-filter-ccs": "CC フィルター",
  "sequencer-midi-outputs-section": "出力",
  "sequencer-midi-channel": "チャンネル",
  "sequencer-midi-no-inputs":
    "MIDI 入力が見つかりません。キーボードを接続するか、loopMIDI のポートを使ってください。",
  "sequencer-output-voice": "ボイス",
  "sequencer-output-none": "なし",
  "sequencer-output-disconnected": "{name}（未接続）",
  "sequencer-builtin-synth": "内蔵シンセ",
  "sequencer-midi-unsupported":
    "このブラウザーは Web MIDI に対応していません。Chrome または Edge を使ってください。",
  "sequencer-midi-error": "MIDI にアクセスできませんでした:",
  "sequencer-midi-permission-hint":
    "ブラウザーが MIDI をブロックしました。このサイトの設定（アドレスバー左端のアイコン）で MIDI デバイスを許可してから、もう一度お試しください。",
  "sequencer-midi-retry": "再試行",
  "sequencer-midi-enable": "MIDI を有効にする",
  "sequencer-midi-enable-hint":
    "MIDI デバイスを使うには、midiseq への許可が必要です。",
  "sequencer-no-input":
    "録音元がありません。設定で MIDI 入力にチェックを入れてください。",
  "sequencer-no-output":
    "出力先がありません。音を聴くには、MIDI 設定で出力を選んでください。",
  "sequencer-status-open-settings": "設定を開く",
  "sequencer-synth-loading": "内蔵音源を起動中…",
  "sequencer-status-dismiss": "閉じる",
  "sequencer-synth-error": "内蔵音源を起動できませんでした:",
  "sequencer-synth-mute": "内蔵シンセをミュート",
  "sequencer-synth-mute-hint":
    "MIDI 出力設定で内蔵シンセのオン/オフを切り替えます",
  "sequencer-soundfont-hint":
    "内蔵シンセが鳴らす音色です。手持ちの SF2、SF3、DLS ファイルを追加できます。",
  "sequencer-soundfont-list": "SoundFont",
  "sequencer-soundfont-add": "追加",
  "sequencer-soundfont-adding": "追加中…",
  "sequencer-soundfont-remove": "{name} を削除",
  "sequencer-soundfont-by": "作成者: {author}",
  "sequencer-soundfont-loading": "読み込み中…",
  "sequencer-soundfont-add-error": "追加できませんでした:",
  "sequencer-error-not-soundfont": "{name} は SoundFont ではありません",
  "sequencer-error-soundfont-fetch":
    "SoundFont を取得できませんでした（{status}）",
  "sequencer-error-soundfont-gone": "その SoundFont はもう保存されていません",
  "sequencer-soundfont-saved-notice":
    "追加した SoundFont はこのブラウザーに保存されます。",
  "sequencer-soundfont-off-hint":
    "「MIDI」で内蔵シンセを出力に選ぶと聞こえるようになります。",
}

export default ja
