export default {
  en: {
    "sequencer-app-name": "midiseq",
    "sequencer-untitled": "Untitled",
    "sequencer-panel": "Sequencer",
    "sequencer-jumps": "Jumps",
    "sequencer-grid": "Sequence Grid",
    "sequencer-step-editor": "Step Editor",
    "sequencer-voices": "Voices",
    "sequencer-action-hang": "Hang",
    "sequencer-action-bump": "Bump",
    "sequencer-action-flip": "Flip",
    "sequencer-action-shift": "Shift",
    "sequencer-play": "Play",
    "sequencer-stop": "Stop",
    "sequencer-panic": "Panic",
    "sequencer-bpm": "BPM",
    "sequencer-step": "Step",
    "sequencer-record": "Record",
    "sequencer-undo": "Undo",
    "sequencer-redo": "Redo",
    "sequencer-size": "Size",
    "sequencer-pace": "Pace",
    "sequencer-direction": "Direction",
    "sequencer-loop": "Loop",
    "sequencer-loop-end": "Loop end",
    "sequencer-sync-voices": "Sync voices",
    "sequencer-shift-amt": "Shift amt",
    "sequencer-max-notes": "Max notes",
    "sequencer-voice": "Voice",
    "sequencer-voice-enable": "Enable",
    "sequencer-voice-length": "Length",
    "sequencer-voice-rule": "Rule",
    "sequencer-voice-offset": "Offset",
    "sequencer-voice-velocity": "Velocity",
    "sequencer-voice-channel": "Channel",
    "sequencer-voice-pattern-length": "Pattern",
    "sequencer-voice-dot": "Dot",
    "sequencer-tempo": "Tempo",
    "sequencer-midi-outputs": "MIDI",
    "sequencer-midi-outputs-section": "Outputs",
    "sequencer-midi-input-section": "Input",
    "sequencer-midi-input": "Port",
    "sequencer-midi-channel": "Channel",
    "sequencer-midi-omni": "Omni",
    "sequencer-midi-no-inputs":
      "No MIDI inputs found. Connect a keyboard, or use a loopMIDI port.",
    "sequencer-output-all": "All",
    "sequencer-output-voice": "Voice",
    "sequencer-output-none": "None",
    "sequencer-output-disconnected": "disconnected",
    "sequencer-midi-unsupported":
      "This browser doesn't support Web MIDI. Use Chrome or Edge.",
    "sequencer-midi-error": "Couldn't access MIDI:",
    "sequencer-midi-permission-hint":
      "The browser blocked MIDI. Allow MIDI devices in this site's settings (the icon at the left of the address bar), then try again.",
    "sequencer-midi-retry": "Try again",
    "sequencer-midi-enable": "Enable MIDI",
    "sequencer-midi-enable-hint":
      "midiseq needs your permission to use MIDI devices.",
    "sequencer-midi-no-outputs":
      "No MIDI outputs found. On Windows, create a port in loopMIDI.",
  },
}
