export default {
  en: {
    "sequencer-app-name": "midiseq",
    "sequencer-untitled": "Untitled",
    "sequencer-panel": "Sequencer",
    "sequencer-grid": "Sequence Grid",
    "sequencer-step-editor": "Step Editor",
    "sequencer-voices": "Voices",
    "sequencer-settings-panes": "Settings panes",
    "sequencer-action-hang": "Hang",
    "sequencer-action-bump": "Bump",
    "sequencer-action-flip": "Flip",
    "sequencer-action-shift": "Shift",
    "sequencer-play": "Play",
    "sequencer-stop": "Stop",
    "sequencer-bpm": "BPM",
    "sequencer-step": "Step",
    "sequencer-record": "Record",
    "sequencer-file": "File",
    "sequencer-clear-all": "Clear all",
    "sequencer-file-new": "New",
    "sequencer-file-open": "Open…",
    "sequencer-file-save": "Save",
    "sequencer-file-save-as": "Save as…",
    "sequencer-undo": "Undo",
    "sequencer-redo": "Redo",
    "sequencer-size": "Size",
    "sequencer-pace": "Pace",
    "sequencer-direction": "Direction",
    "sequencer-loop": "Loop",
    "sequencer-loop-end": "Loop end",
    "sequencer-sync-voices": "Sync voices",
    "sequencer-shift-amt": "Shift amt",
    "sequencer-max-notes": "Step notes",
    "sequencer-voice": "Voice",
    "sequencer-voice-enable": "Enable",
    "sequencer-voice-length": "Length",
    "sequencer-voice-rule": "Rule",
    "sequencer-voice-offset": "Offset",
    "sequencer-voice-velocity": "Velocity",
    "sequencer-voice-channel": "Channel",
    "sequencer-voice-instrument": "Instrument",
    "sequencer-voice-pattern-length": "Pattern",
    "sequencer-voice-dot": "Dot",
    "sequencer-tempo": "Tempo",
    "sequencer-step-state": "State",
    "sequencer-step-state-normal": "Normal",
    "sequencer-step-state-rest": "Rest",
    "sequencer-step-state-skip": "Skip",
    "sequencer-step-note": "Note",
    "sequencer-step-add-note": "Add note",
    "sequencer-step-remove-note": "Remove note",
    "sequencer-step-no-notes": "No notes. Record, or add one.",
    "sequencer-step-over-limit":
      "Notes past the limit are dimmed and stay silent.",
    "sequencer-step-trim": "Trim to limit",
    "sequencer-step-ccs": "Velocity & CCs",
    "sequencer-step-add-cc": "Add CC",
    "sequencer-step-more-lanes": "More lanes",
    "sequencer-step-remove-cc": "Remove CC",
    "sequencer-velocity-edit-hint":
      "Each note is a point on the line. Drag a point or the line to set its velocity; click a point to return its note to the voice's. Near a dashed line a note snaps onto that accent; one dot's notes move together. B switches to Draw.",
    "sequencer-velocity-draw-hint":
      "Drag across the notes to paint their velocities. B switches back to Edit.",
    "sequencer-velocity-voice-off": "off",
    "sequencer-step-cc": "CC",
    "sequencer-envelope": "Envelope",
    "sequencer-envelope-cc-number": "CC number",
    "sequencer-envelope-cc-channel": "CC channel",
    "sequencer-envelope-edit": "Edit",
    "sequencer-envelope-draw": "Draw",
    "sequencer-envelope-grid": "Grid",
    "sequencer-envelope-edit-hint":
      "Click the line to add a point, or double-click anywhere. Drag a point or the line to move it; click a point to delete it. Alt skips the grid; B switches to Draw.",
    "sequencer-envelope-draw-hint":
      "Drag to paint values across the grid. Alt paints freely; B switches back to Edit.",
    "sequencer-action-latch": "Latch",
    "sequencer-preview": "Audition step",
    "sequencer-mark": "Mark",
    "sequencer-jump-rule": "Rule",
    "sequencer-jump-dest": "Destination",
    "sequencer-jump-normal": "Normal",
    "sequencer-jump-pick": "Pick",
    "sequencer-jump-add": "Jump rule",
    "sequencer-jump-remove": "Remove jump",
    "sequencer-jump-none": "None",
    "sequencer-jump-next": "Next",
    "sequencer-jump-hint": "Click a step in the grid to set it.",
    "sequencer-dot-hint": "Right-click a dot for its step options.",
    "sequencer-voice-patterns": "Patterns",
    "sequencer-voice-pattern": "pattern",
    "sequencer-voice-select": "Select voice",
    "sequencer-patterns-export": "Export patterns",
    "sequencer-patterns-import": "Import patterns",
    "sequencer-dot-articulation": "Articulation",
    "sequencer-dot-articulation-none": "None",
    "sequencer-dot-articulation-hold": "Hold",
    "sequencer-dot-articulation-tie": "Tie",
    "sequencer-dot-accent": "Accent",
    "sequencer-dot-ratchet": "Ratchet",
    "sequencer-dot-probability": "Probability",
    "sequencer-dot-condition": "Condition",
    "sequencer-dot-none": "None",
    "sequencer-dot-always": "Always",
    "sequencer-dot-last": "Last",
    "sequencer-dot-not-last": "Not last",
    "sequencer-dot-reset": "Reset dot",
    "sequencer-step-copy": "Copy",
    "sequencer-step-paste": "Paste",
    "sequencer-step-clear": "Clear",
    "sequencer-settings": "Settings",
    "sequencer-settings-general": "General",
    "sequencer-settings-midi": "MIDI",
    "sequencer-settings-close": "Close",
    "sequencer-theme": "Theme",
    "sequencer-accent-amount": "Accent amount",
    "sequencer-accent-amount-hint":
      "How far an accent moves a note's velocity, up or down.",
    "sequencer-theme-dark": "Dark",
    "sequencer-theme-light": "Light",
    "sequencer-midi-inputs-section": "Inputs",
    "sequencer-midi-voice-outputs": "Voice outputs",
    "sequencer-midi-voice-outputs-hint":
      "A voice can also go to a port of its own, alongside the ports above.",
    "sequencer-clock": "Clock",
    "sequencer-clock-send": "Send MIDI clock",
    "sequencer-clock-hint":
      "Start, stop and 24 ticks a beat go to every ticked output, so anything listening follows midiseq's tempo.",
    "sequencer-clock-follow": "Take tempo from MIDI clock",
    "sequencer-clock-follow-hint":
      "A clock arriving at a ticked input sets the tempo. Start and stop are ignored — playing and stopping stay yours.",
    "sequencer-filter": "Input filter",
    "sequencer-filter-hint": "What the ticked inputs are allowed to send in.",
    "sequencer-filter-channels": "Channels",
    "sequencer-filter-none": "None",
    "sequencer-filter-all": "All",
    "sequencer-filter-range": "Note range",
    "sequencer-filter-low": "Lowest note",
    "sequencer-filter-high": "Highest note",
    "sequencer-filter-transpose": "Transpose",
    "sequencer-filter-semitones": "st",
    "sequencer-filter-ccs": "CC filter",
    "sequencer-midi-outputs-section": "Outputs",
    "sequencer-midi-input-section": "Input",
    "sequencer-midi-input": "Port",
    "sequencer-midi-channel": "Channel",
    "sequencer-midi-omni": "Omni",
    "sequencer-midi-no-inputs":
      "No MIDI inputs found. Connect a keyboard, or use a loopMIDI port.",
    "sequencer-output-all": "All",
    "sequencer-output-voice": "Voice",
    "sequencer-output-none": "None",
    "sequencer-output-disconnected": "disconnected",
    "sequencer-midi-unsupported":
      "This browser doesn't support Web MIDI. Use Chrome or Edge.",
    "sequencer-midi-error": "Couldn't access MIDI:",
    "sequencer-midi-permission-hint":
      "The browser blocked MIDI. Allow MIDI devices in this site's settings (the icon at the left of the address bar), then try again.",
    "sequencer-midi-retry": "Try again",
    "sequencer-midi-enable": "Enable MIDI",
    "sequencer-midi-enable-hint":
      "midiseq needs your permission to use MIDI devices.",
    "sequencer-no-input":
      "Nothing to record from — tick a MIDI input in Settings",
    "sequencer-no-output":
      "Nothing is routed — pick an output in MIDI to hear this",
    "sequencer-synth-loading": "Starting the built-in sound…",
    "sequencer-synth-error": "The built-in sound didn't start:",
    "sequencer-midi-no-outputs":
      "No MIDI outputs found. On Windows, create a port in loopMIDI.",
  },
}
