import type { Translation } from "./en"

// Slovak
const sk: Translation = {
  "sequencer-preview-pending": "Pripravuje sa ukážka…",
  "sequencer-preview-unavailable": "Ukážka nie je k dispozícii",
  "sequencer-panel": "Sekvencér",
  "sequencer-grid": "Mriežka",
  "sequencer-step-editor": "Editor kroku",
  "sequencer-voices": "Hlasy",
  "sequencer-settings-panes": "Panely nastavení",
  "sequencer-action-hold": "Držať",
  "sequencer-action-sync": "Sync",
  "sequencer-action-flip": "Otočiť",
  "sequencer-action-transpose": "Transponovať",
  "sequencer-action-hold-hint":
    "Podrží sekvencér na aktuálnom kroku, kým hlasy hrajú ďalej (H)",
  "sequencer-action-sync-hint":
    "Vybraný hlas hrá rýchlosťou sekvencéra, jednu notu na krok (Y)",
  "sequencer-action-flip-hint":
    "Vymení riadky a stĺpce mriežky, od nasledujúceho kroku (F)",
  "sequencer-action-transpose-hint":
    "Transponuje nové noty o hodnotu nastavenia Transpozícia v sekvencéri (T)",
  "sequencer-action-latch-hint":
    "Kliknutie zapne akciu, až kým na ňu znova nekliknete, a nie iba počas jej držania",
  "sequencer-actions": "Akcie",
  "sequencer-action-off": "Vypnuté",
  "sequencer-action-on": "Zapnuté",
  "sequencer-play": "Prehrať",
  "sequencer-pause": "Pauza",
  "sequencer-stop": "Stop",
  "sequencer-bpm-value": "{bpm} BPM",
  "sequencer-step-number": "Krok {step}",
  "sequencer-steps-count":
    "{count, plural, one {# krok} few {# kroky} other {# krokov}}",
  "sequencer-ccs-count": "{count, plural, one {# CC} few {# CC} other {# CC}}",
  "sequencer-record": "Nahrávať",
  "sequencer-file": "Súbor",
  "sequencer-edit": "Upraviť",
  "sequencer-file-new": "Nový",
  "sequencer-file-open": "Otvoriť…",
  "sequencer-file-save": "Uložiť",
  "sequencer-file-save-as": "Uložiť ako…",
  "sequencer-file-export-midi": "Exportovať MIDI…",
  "sequencer-file-import-midi": "Importovať MIDI…",
  "sequencer-file-render-audio": "Renderovať zvuk…",
  "sequencer-file-recent-patches": "Nedávne patche",
  "sequencer-file-recent-midi": "Nedávne importy MIDI",
  "sequencer-confirm-discard": "Tento patch má neuložené zmeny. Zahodiť ich?",
  "sequencer-recent-gone":
    "Súbor {name} sa nenašiel. Možno bol presunutý alebo odstránený.",
  "sequencer-failed-open-recent": "Súbor {name} sa nepodarilo otvoriť.",
  "sequencer-failed-open-file": "Súbor sa nepodarilo otvoriť.",
  "sequencer-failed-read-patch": "Tento súbor sa nepodarilo otvoriť.",
  "sequencer-failed-save-patch": "Patch sa nepodarilo uložiť.",
  "sequencer-failed-export-patterns": "Vzory sa nepodarilo exportovať.",
  "sequencer-failed-import-patterns": "Vzory sa nepodarilo importovať.",
  "sequencer-failed-read-patterns": "Tieto vzory sa nepodarilo importovať.",
  "sequencer-failed-export-midi": "MIDI sa nepodarilo exportovať.",
  "sequencer-failed-export-step": "Krok sa nepodarilo exportovať ako MIDI.",
  "sequencer-failed-open-midi": "Súbor MIDI sa nepodarilo otvoriť.",
  "sequencer-failed-read-midi": "Súbor MIDI sa nepodarilo prečítať.",
  "sequencer-failed-read-midi-file": "Tento súbor sa nepodarilo importovať.",
  "sequencer-failed-save-audio": "Zvuk sa nepodarilo uložiť.",
  "sequencer-failed-load-soundfont": "SoundFont sa nepodarilo načítať.",
  "sequencer-failed-render-audio": "Zvuk sa nepodarilo renderovať.",
  "sequencer-error-read-denied":
    "Prehliadač nedostal povolenie súbor prečítať.",
  "sequencer-import-midi": "Import MIDI: {name}",
  "sequencer-import-action": "Importovať",
  "sequencer-import-nothing": "V tomto úseku nie je čo importovať",
  "sequencer-import-fills": "Vyplní kroky {first}–{last} z {total}",
  "sequencer-import-round": "{times}× dookola",
  "sequencer-import-dealt":
    "{steps, plural, one {# krok} few {# kroky} other {# krokov}} po {notes, plural, one {# note} few {# notách} other {# notách}}",
  "sequencer-import-dont-fit":
    "{count, plural, one {# nota sa nezmestí} few {# noty sa nezmestia} other {# nôt sa nezmestí}}",
  "sequencer-import-preview": "Ukážka: {name}",
  "sequencer-import-loading": "Načítava sa {name}…",
  "sequencer-import-filter": "Filter MIDI",
  "sequencer-import-options": "Možnosti",
  "sequencer-import-tracks-chosen":
    "{chosen} z {count, plural, one {# stopy} few {# stôp} other {# stôp}}",
  "sequencer-import-notes-a-step":
    "{count, plural, one {# nota na krok} few {# noty na krok} other {# nôt na krok}}",
  "sequencer-import-from": "od kroku {step}",
  "sequencer-import-looping": "opakovane",
  "sequencer-import-filter-hint":
    "Vychádza z filtra MIDI vstupu v Nastaveniach; zmeny tu platia iba pre tento import. Noty, ktoré filter neprepustí, sú sivé a neimportujú sa.",
  "sequencer-import-filtered": "odfiltrované",
  "sequencer-import-all-channels": "všetky kanály",
  "sequencer-import-no-channels": "žiadne kanály",
  "sequencer-import-all-notes": "všetky noty",
  "sequencer-import-snap": "Prichytiť",
  "sequencer-import-snap-bar": "Takt",
  "sequencer-import-snap-beat": "Doba",
  "sequencer-import-snap-off": "Vypnuté",
  "sequencer-import-start": "Začiatok importu",
  "sequencer-import-end": "Koniec importu",
  "sequencer-import-bar": "takt {bar}",
  "sequencer-import-parts": "Stopy",
  "sequencer-import-no-notes": "Tento súbor neobsahuje žiadne noty.",
  "sequencer-import-track": "Stopa {track}",
  "sequencer-import-notes":
    "{count, plural, one {# nota} few {# noty} other {# nôt}}",
  "sequencer-import-notes-per-step": "Noty na krok",
  "sequencer-import-drums": "bicie",
  "sequencer-import-no-ccs": "Tento súbor neposiela žiadne CC.",
  "sequencer-import-changes":
    "{count, plural, one {# zmena} few {# zmeny} other {# zmien}}",
  "sequencer-import-steps": "Kroky",
  "sequencer-import-size-fit": "Prispôsobiť",
  "sequencer-import-size-fit-hint":
    "Nastaví veľkosť sekvencie tak, aby končila posledným krokom, ktorý import vyplní",
  "sequencer-import-from-step": "Od kroku",
  "sequencer-import-loop": "Opakovať, kým sa mriežka nezaplní",
  "sequencer-import-tempo": "Prevziať tempo súboru",
  "sequencer-import-no-tempo": "súbor ho neuvádza",
  "sequencer-import-hint":
    "Noty začínajúce v úseku idú do krokov v poradí, v akom hrajú, po toľkých na krok, koľko zvolíte — z toho sa stanú Noty kroku — každá klávesa raz na krok. Červené noty sa do mriežky nezmestia. Z CC sa stanú schodovité obálky nad notami každého kroku. Vyplnené kroky stratia svoj pôvodný obsah; jedno Späť celý import vráti.",
  "sequencer-import-settings-hint":
    "Východiskové hodnoty pre Súbor → Importovať MIDI. Každý import si ich môže zmeniť sám pre seba.",
  "sequencer-import-skip-drums": "Vynechať kanál bicích",
  "sequencer-import-skip-drums-note": "kanál 10",
  "sequencer-import-ccs-default": "Preniesť CC zo súboru",
  "sequencer-import-snap-setting": "Prichytávanie úseku",
  "sequencer-file-export-step-midi": "Exportovať MIDI kroku…",
  "sequencer-export-step-midi": "Export MIDI: krok {step}",
  "sequencer-export-step-hint":
    "Krok v editore tak, ako ho sekvencia prvýkrát dosiahne: noty a CC, ktoré hrá, v dĺžke jedného kroku. Šanca a náhodné pravidlá sa losujú nanovo.",
  "sequencer-export-settings-hint":
    "Východiskové hodnoty pre Súbor → Exportovať MIDI a Exportovať MIDI kroku a obsah kroku vytiahnutého z mriežky: pretiahnite krok na plochu, do priečinka alebo do DAW a hneď dostanete jeho MIDI súbor s týmito nastaveniami. Uvedené CC sú tie, ktoré táto sekvencia posiela.",
  "sequencer-export-midi": "Export MIDI",
  "sequencer-export-midi-action": "Exportovať",
  "sequencer-export-cancel": "Zrušiť",
  "sequencer-export-voices": "Hlasy",
  "sequencer-export-ccs": "CC",
  "sequencer-export-all-ccs": "Všetky CC",
  "sequencer-export-no-ccs": "Táto sekvencia neposiela žiadne CC.",
  "sequencer-export-modulation-ccs": "CC modulácie",
  "sequencer-export-modulation-ccs-note": "tie, ktoré riadia nastavenia",
  "sequencer-export-mod": "mod {source}",
  "sequencer-export-tracks": "Stopy",
  "sequencer-export-layout-perVoice": "Stopa pre každý hlas",
  "sequencer-export-layout-combined": "Všetko v jednej stope",
  "sequencer-export-voice-off": "vypnutý",
  "sequencer-export-passes": "Prechody",
  "sequencer-export-bars":
    "{count, plural, one {# takt} few {# takty} many {# taktu} other {# taktov}}",
  "sequencer-export-hint":
    "Celá sekvencia tak, ako hrá od začiatku: každý hlas na vlastnom kanáli so svojím nástrojom a CC na svojich kanáloch. Šanca a náhodné pravidlá sa losujú nanovo.",
  "sequencer-render-audio": "Renderovať zvuk",
  "sequencer-render-audio-action": "Renderovať",
  "sequencer-render-hint":
    "Celá sekvencia tak, ako hrá od začiatku, cez vstavaný zvuk: {font}. Šanca a náhodné pravidlá sa losujú nanovo.",
  "sequencer-render-name": "Názov súboru",
  "sequencer-render-format": "Formát",
  "sequencer-render-format-wav": "WAV",
  "sequencer-render-format-mp3": "MP3",
  "sequencer-render-sample-rate": "Vzorkovanie",
  "sequencer-render-bit-depth": "Bitová hĺbka",
  "sequencer-render-bit-depth-16": "16-bit",
  "sequencer-render-bit-depth-24": "24-bit",
  "sequencer-render-bit-depth-32": "32-bit float",
  "sequencer-render-bitrate": "Dátový tok",
  "sequencer-render-channels": "Kanály",
  "sequencer-render-channels-2": "Stereo",
  "sequencer-render-channels-1": "Mono",
  "sequencer-render-tail": "Dozvuk",
  "sequencer-render-tail-note": "na doznenie po poslednom kroku",
  "sequencer-render-normalize": "Normalizovať",
  "sequencer-render-normalize-note": "najhlasnejšia špička na −1 dB",
  "sequencer-render-loading": "Načítava sa SoundFont…",
  "sequencer-render-measuring": "Meria sa úroveň…",
  "sequencer-render-rendering": "Renderuje sa…",
  "sequencer-render-saving": "Ukladá sa…",
  "sequencer-render-progress": "Priebeh renderovania",
  "sequencer-mod-seqX": "Sekv. X",
  "sequencer-mod-seqY": "Sekv. Y",
  "sequencer-mod-phase": "Fáza",
  "sequencer-mod-actionOr": "Akcie",
  "sequencer-mod-voice1Random": "Náhoda hlasu 1",
  "sequencer-mod-voice2Random": "Náhoda hlasu 2",
  "sequencer-mod-voice3Random": "Náhoda hlasu 3",
  "sequencer-mod-voice4Random": "Náhoda hlasu 4",
  "sequencer-modulation": "Modulácia",
  "sequencer-modulation-of": "Modulácia: {target}",
  "sequencer-modulation-settings": "Nastavenia modulácie: {target}",
  "sequencer-modulation-by": "Modulované pomocou CC {cc}",
  "sequencer-modulation-cc": "CC",
  "sequencer-modulation-cc-of": "CC pre {target}",
  "sequencer-modulation-from": "Od",
  "sequencer-modulation-to": "Do",
  "sequencer-modulation-values":
    "{count, plural, one {# hodnota} few {# hodnoty} other {# hodnôt}}",
  "sequencer-modulation-hint":
    "Krok s obálkou pre toto CC toto nastavenie počas hrania mení; každý iný krok ponechá vlastnú hodnotu poľa. Hodnoty obálky sú tie medzi Od a Do.",
  "sequencer-modulation-action-hint":
    "Krok s obálkou pre toto CC akciu zapne alebo vypne bez ohľadu na jej tlačidlo: Držať a Otočiť na konci kroku, Sync na jeho začiatku, Transponovať pri každej note. Každý iný krok to nechá na tlačidlo.",
  "sequencer-modulation-taken": "CC {cc}: Už moduluje {target}",
  "sequencer-modulation-on-steps":
    "CC {cc}: Už je na {count, plural, one {# kroku} few {# krokoch} other {# krokoch}}",
  "sequencer-modulation-on":
    "{count, plural, one {Na kroku {steps}} few {Na krokoch {steps}} other {Na krokoch {steps}}}",
  "sequencer-modulation-on-none": "Nie je na žiadnom kroku",
  "sequencer-modulation-assign": "Modulovať",
  "sequencer-modulation-show": "Zobraziť na kroku {step}",
  "sequencer-modulation-remove": "Odstrániť",
  "sequencer-modulation-remove-hint":
    "CC prestane modulovať toto nastavenie. Jeho obálky ostanú ako CC.",
  "sequencer-modulation-tab-transpose-fit": "Do stupnice",
  "sequencer-modulation-tab-sequencer-pace": "Rýchlosť sekv.",
  "sequencer-modulation-tab-sequencer-transpose": "Transp. sekv.",
  "sequencer-modulation-tab-sequencer-transpose-fit": "Pri nahrávaní",
  "sequencer-modulation-modulates": "Moduluje {target}",
  "sequencer-undo": "Späť",
  "sequencer-redo": "Znova",
  "sequencer-size": "Veľkosť",
  "sequencer-pace": "Rýchlosť",
  "sequencer-direction": "Smer",
  "sequencer-direction-fwd": "Vpred",
  "sequencer-direction-bwd": "Vzad",
  "sequencer-direction-fwdbwd": "Vpred / vzad",
  "sequencer-direction-bwdfwd": "Vzad / vpred",
  "sequencer-direction-random": "Náhodne",
  "sequencer-direction-random+": "Náhodne+",
  "sequencer-loop": "Slučka",
  "sequencer-loop-recorded": "Nahraté",
  "sequencer-loop-all": "Všetky",
  "sequencer-loop-custom": "Vlastné",
  "sequencer-loop-end": "Koniec slučky",
  "sequencer-sync-voices": "Synchr. hlasy",
  "sequencer-transpose-amt": "Transpozícia",
  "sequencer-transpose-fit": "Do stupnice",
  "sequencer-record-fit": "Pri nahrávaní",
  "sequencer-max-notes": "Noty kroku",
  "sequencer-voice": "Hlas",
  "sequencer-voice-enable": "Zapnutý",
  "sequencer-voice-length": "Dĺžka",
  "sequencer-voice-rule": "Pravidlo",
  "sequencer-rule-nth": "N-tá",
  "sequencer-rule-lowest": "Najnižšia",
  "sequencer-rule-highest": "Najvyššia",
  "sequencer-rule-random": "Náhodná",
  "sequencer-rule-up": "Nahor",
  "sequencer-rule-down": "Nadol",
  "sequencer-rule-updown": "Nahor / nadol",
  "sequencer-rule-downup": "Nadol / nahor",
  "sequencer-rule-updown+": "Nahor / nadol +",
  "sequencer-rule-downup+": "Nadol / nahor +",
  "sequencer-rule-rise": "Stúpanie",
  "sequencer-rule-fall": "Klesanie",
  "sequencer-rule-outsidein": "Zvonka dnu",
  "sequencer-rule-insideout": "Zvnútra von",
  "sequencer-rule-ends": "Okraje",
  "sequencer-rule-shuffle": "Premiešanie",
  "sequencer-rule-walk": "Prechádzka",
  "sequencer-rule-norepeat": "Bez opakovania",
  "sequencer-voice-velocity": "Velocity",
  "sequencer-voice-velocity-of": "Velocity hlasu {voice}",
  "sequencer-voice-channel": "Kanál",
  "sequencer-voice-instrument": "Nástroj",
  "sequencer-voice-pattern-length": "Vzor",
  "sequencer-voice-dot": "Bodka",
  "sequencer-voice-dot-of": "Hlas {voice}, bodka {dot}",
  "sequencer-tempo": "Tempo",
  "sequencer-step-state": "Stav",
  "sequencer-step-state-normal": "Normálny",
  "sequencer-step-state-rest": "Pomlčka",
  "sequencer-step-state-skip": "Preskočiť",
  "sequencer-step-note": "Nota",
  "sequencer-step-add-note": "Pridať notu",
  "sequencer-step-remove-note": "Odstrániť notu",
  "sequencer-step-remove-note-of": "Odstrániť notu {note}",
  "sequencer-step-no-notes": "Žiadne noty. Nahrajte alebo pridajte nejakú.",
  "sequencer-step-over-limit": "Noty nad limitom sú zašednuté a nehrajú.",
  "sequencer-step-trim": "Orezať na limit",
  "sequencer-step-out-of-scale": "Mimo stupnice",
  "sequencer-step-ccs": "Velocity a CC",
  "sequencer-step-add-cc": "Pridať CC",
  "sequencer-step-more-lanes": "Ďalšie dráhy",
  "sequencer-step-remove-cc": "Odstrániť CC",
  "sequencer-step-remove-cc-modulation": "Odstrániť CC aj moduláciu: {target}",
  "sequencer-step-cc-values": "Hodnoty CC",
  "sequencer-step-cc-copy": "Kopírovať hodnoty",
  "sequencer-step-cc-paste": "Prilepiť hodnoty",
  "sequencer-step-cc-clear": "Vymazať hodnoty z tohto kroku",
  "sequencer-velocity-voice-off": "vypnutý",
  "sequencer-step-cc": "CC",
  "sequencer-channel-short": "kan. {channel}",
  "sequencer-envelope-not-on-step":
    "na tomto kroku nie je — pridajte ju kreslením",
  "sequencer-envelope": "Obálka",
  "sequencer-envelope-cc-number": "Číslo CC",
  "sequencer-envelope-cc-channel": "Kanál CC",
  "sequencer-envelope-edit": "Upraviť",
  "sequencer-envelope-edit-tool": "Upraviť body",
  "sequencer-envelope-draw": "Kresliť",
  "sequencer-envelope-erase": "Mazať",
  "sequencer-envelope-erase-hint":
    "Mazať body: kliknite na ne alebo cez ne prejdite ťahaním",
  "sequencer-envelope-grid": "Mriežka",
  "sequencer-envelope-point": "Bod",
  "sequencer-envelope-point-value": "Hodnota",
  "sequencer-envelope-point-value-of": "Hodnota bodu {point}",
  "sequencer-envelope-point-delete": "Odstrániť bod",
  "sequencer-envelope-steps": "Schody",
  "sequencer-envelope-steps-hint":
    "Schody: každá hodnota platí až do ďalšieho bodu, potom skočí",
  "sequencer-envelope-ramps": "Rampy",
  "sequencer-envelope-ramps-hint":
    "Rampy: priame čiary z každého bodu k ďalšiemu",
  "sequencer-collapse-scale":
    "Zbaliť stupnicu — zobraziť iba klávesy, ktoré sekvencia hrá",
  "sequencer-envelope-ruler":
    "Pravítko — ťahaním nahor priblížite, nadol oddialite, do strán posúvate",
  "sequencer-action-latch": "Aretácia",
  "sequencer-preview": "Odposluch kroku",
  "sequencer-patch-name": "Názov patchu",
  "sequencer-patch-name-of": "Názov patchu: {name}",
  "sequencer-patch-rename": "Premenovať patch",
  "sequencer-jump-rule": "Pravidlo",
  "sequencer-jump-dest": "Cieľ",
  "sequencer-jump-normal": "Normálne",
  "sequencer-jump-pick-dest": "Vybrať cieľ",
  "sequencer-jump-pick-normal": "Vybrať normálny krok",
  "sequencer-jump-add": "Pravidlo skoku",
  "sequencer-jump-remove": "Odstrániť skok",
  "sequencer-jump-none": "Žiadny",
  "sequencer-jump-next": "Ďalší",
  "sequencer-jump-always": "Vždy",
  "sequencer-jump-last": "Predošlý",
  "sequencer-jump-not-last": "Nie predošlý",
  "sequencer-jump-hint": "Kliknutím na krok v mriežke ho nastavíte.",
  "sequencer-dot-collision":
    "Rovnaká nota ako iný hlas: {note} · {count, plural, one {Hlas {voices}} few {Hlasy {voices}} other {Hlasy {voices}}}",
  "sequencer-dot-hint": "Pravým kliknutím na bodku otvoríte jej možnosti.",
  "sequencer-voice-patterns": "Vzory",
  "sequencer-voice-pattern": "Vzor hlasu {voice}",
  "sequencer-voice-select": "Vybrať hlas {voice}",
  "sequencer-voice-mute": "Stlmiť",
  "sequencer-voice-mute-of": "Stlmiť hlas {voice}",
  "sequencer-voice-solo": "Sólo",
  "sequencer-voice-solo-of": "Sólo hlasu {voice}",
  "sequencer-patterns-export": "Exportovať vzory",
  "sequencer-patterns-import": "Importovať vzory",
  "sequencer-dot-articulation": "Artikulácia",
  "sequencer-dot-articulation-none": "Žiadna",
  "sequencer-dot-articulation-hold": "Výdrž",
  "sequencer-dot-articulation-tie": "Ligatúra",
  "sequencer-dot-accent": "Akcent",
  "sequencer-dot-ratchet": "Ratchet",
  "sequencer-dot-probability": "Šanca",
  "sequencer-dot-condition": "Podmienka",
  "sequencer-dot-none": "Žiadny",
  "sequencer-dot-always": "Vždy",
  "sequencer-dot-last": "Predošlá",
  "sequencer-dot-not-last": "Nie predošlá",
  "sequencer-dot-condition-always-hint":
    "Vždy: hrá zakaždým, keď vzor dosiahne túto bodku",
  "sequencer-dot-condition-2:2-hint":
    "2:2: v prvom cykle ticho, hrá v druhom z každých dvoch (cykly 2, 4, 6…)",
  "sequencer-dot-condition-3:3-hint":
    "3:3: v cykloch 1 a 2 ticho, hrá v treťom z každých troch (cykly 3, 6, 9…)",
  "sequencer-dot-condition-4:4-hint":
    "4:4: v cykloch 1 až 3 ticho, hrá vo štvrtom z každých štyroch (cykly 4, 8, 12…)",
  "sequencer-dot-condition-1x-hint":
    "1x: jeden cyklus hrá, ďalší vynechá a tak ďalej (cykly 1, 3, 5…)",
  "sequencer-dot-condition-2x-hint":
    "2x: hrá dva cykly za sebou, potom tretí vynechá (cykly 1, 2, 4, 5…)",
  "sequencer-dot-condition-3x-hint":
    "3x: hrá tri cykly za sebou, potom štvrtý vynechá (cykly 1, 2, 3, 5…)",
  "sequencer-dot-condition-last-hint":
    "Predošlá: hrá, iba ak hrala bodka tesne pred ňou — nie ak neprešla šancou, vynechala ju podmienka alebo bola vypnutá",
  "sequencer-dot-condition-notLast-hint":
    "Nie predošlá: hrá, iba ak bodka tesne pred ňou nehrala — záloha pre prípad, že neprejde šancou alebo podmienkou",
  "sequencer-dot-reset": "Obnoviť bodku",
  "sequencer-dot-copy": "Kopírovať",
  "sequencer-dot-paste": "Prilepiť",
  "sequencer-dot-shift-left": "Posunúť vľavo",
  "sequencer-dot-shift-right": "Posunúť vpravo",
  "sequencer-dot-swap-left": "Vymeniť vľavo",
  "sequencer-dot-swap-right": "Vymeniť vpravo",
  "sequencer-dot-insert-before": "Vložiť pred",
  "sequencer-dot-insert-after": "Vložiť za",
  "sequencer-step-copy": "Kopírovať",
  "sequencer-step-paste": "Prilepiť",
  "sequencer-step-clear": "Vyprázdniť",
  "sequencer-step-insert-before": "Vložiť pred",
  "sequencer-step-insert-after": "Vložiť za",
  "sequencer-step-delete": "Odstrániť",
  "sequencer-scale": "Stupnica",
  "sequencer-scale-tonic": "Tónika stupnice",
  "sequencer-scale-none": "Chromatická",
  "sequencer-scale-common": "Bežné",
  "sequencer-scale-more": "Ďalšie",
  "sequencer-scale-fit": "Mimo stupnice",
  "sequencer-scale-fit-up": "Nahor",
  "sequencer-scale-fit-down": "Nadol",
  "sequencer-scale-fit-exclude": "Vynechať",
  "sequencer-scale-fit-ignore": "Ignorovať",
  "sequencer-scale-detected": "Rozpoznané",
  "sequencer-scale-no-notes": "Nie je z čoho rozpoznať",
  "sequencer-scale-detect": "Rozpoznať stupnicu",
  "sequencer-scale-chromatic": "Chromatická",
  "sequencer-scale-moved":
    "{count, plural, one {# posunutá} few {# posunuté} other {# posunutých}}",
  "sequencer-scale-left-out":
    "{count, plural, one {# vynechaná} few {# vynechané} other {# vynechaných}}",
  "sequencer-import-scale-hint":
    "Určená z nôt vo zvolenom úseku. Noty mimo stupnice sa posunú nahor alebo nadol, vynechajú sa, alebo sa nechajú tak.",
  "sequencer-import-min-velocity": "Min. velocity",
  "sequencer-import-min-velocity-note": "Tichšie noty sa vynechajú",
  "sequencer-import-quiet":
    "{count, plural, one {# nota je príliš tichá} few {# noty sú príliš tiché} other {# nôt je príliš tichých}}",
  "sequencer-import-note-low": "Najnižšia nota",
  "sequencer-import-note-high": "Najvyššia nota",
  "sequencer-import-all-parts": "Všetky",
  "sequencer-import-no-parts": "Žiadne",
  "sequencer-settings": "Nastavenia",
  "sequencer-settings-general": "Všeobecné",
  "sequencer-settings-theme": "Vzhľad",
  "sequencer-settings-midi": "MIDI",
  "sequencer-settings-soundfont": "SoundFont",
  "sequencer-settings-export": "Export MIDI",
  "sequencer-settings-import": "Import MIDI",
  "sequencer-settings-close": "Zavrieť",
  "sequencer-language": "Jazyk",
  "sequencer-accent-amount": "Sila akcentu",
  "sequencer-accent-amount-hint":
    "O koľko akcent posunie velocity noty nahor alebo nadol.",
  "sequencer-theme-mode": "Režim",
  "sequencer-theme-mode-light": "Svetlý",
  "sequencer-theme-mode-dark": "Tmavý",
  "sequencer-theme-mode-system": "Systém",
  "sequencer-theme-system-hint":
    "Riadi sa svetlým alebo tmavým nastavením vášho počítača.",
  "sequencer-theme-dark-theme": "Tmavý motív",
  "sequencer-theme-light-theme": "Svetlý motív",
  "sequencer-theme-default": "Predvolený",
  "sequencer-midi-inputs-section": "Vstupy",
  "sequencer-midi-voice-outputs": "Výstupy hlasov",
  "sequencer-midi-voice-outputs-hint":
    "Hlas môže ísť aj na vlastný port, popri portoch vyššie.",
  "sequencer-midi-send-modulation-ccs": "Posielať CC modulácie",
  "sequencer-midi-modulation-ccs-hint":
    "CC, ktoré riadia modulované nastavenia, idú na každý zaškrtnutý výstup ako ostatné CC krokov. Keď je to vypnuté, iba riadia nastavenia.",
  "sequencer-clock": "Hodiny",
  "sequencer-clock-send": "Posielať MIDI hodiny",
  "sequencer-clock-hint":
    "Štart, stop a 24 tikov na dobu idú na každý zaškrtnutý výstup, takže všetko, čo počúva, sleduje tempo midiseq.",
  "sequencer-clock-follow": "Preberať tempo z MIDI hodín",
  "sequencer-clock-follow-hint":
    "Hodiny prichádzajúce na zaškrtnutý vstup nastavujú tempo. Štart a stop sa ignorujú — prehrávanie a zastavenie ostávajú na vás.",
  "sequencer-filter": "Vstupný filter",
  "sequencer-filter-hint": "Čo môžu zaškrtnuté vstupy posielať.",
  "sequencer-filter-channels": "Kanály",
  "sequencer-filter-none": "Žiadne",
  "sequencer-filter-all": "Všetky",
  "sequencer-filter-range": "Rozsah nôt",
  "sequencer-filter-low": "Najnižšia nota",
  "sequencer-filter-high": "Najvyššia nota",
  "sequencer-filter-to": "až",
  "sequencer-filter-transpose": "Transpozícia",
  "sequencer-filter-semitones": "pt",
  "sequencer-filter-ccs": "Filter CC",
  "sequencer-midi-outputs-section": "Výstupy",
  "sequencer-midi-channel": "Kanál",
  "sequencer-midi-no-inputs":
    "Nenašli sa žiadne MIDI vstupy. Pripojte klávesy alebo použite port loopMIDI.",
  "sequencer-output-voice": "Hlas",
  "sequencer-output-none": "Žiadny",
  "sequencer-output-disconnected": "{name} (odpojený)",
  "sequencer-builtin-synth": "Vstavaný syntetizátor",
  "sequencer-midi-unsupported":
    "Tento prehliadač nepodporuje Web MIDI. Použite Chrome alebo Edge.",
  "sequencer-midi-error": "Nepodarilo sa získať prístup k MIDI:",
  "sequencer-midi-permission-hint":
    "Prehliadač zablokoval MIDI. Povoľte MIDI zariadenia v nastaveniach tejto stránky (ikona vľavo v paneli s adresou) a skúste to znova.",
  "sequencer-midi-retry": "Skúsiť znova",
  "sequencer-midi-enable": "Povoliť MIDI",
  "sequencer-midi-enable-hint":
    "midiseq potrebuje vaše povolenie na používanie MIDI zariadení.",
  "sequencer-no-input":
    "Nie je z čoho nahrávať. Zaškrtnite MIDI vstup v Nastaveniach.",
  "sequencer-no-output":
    "Nič nie je smerované. Ak to chcete počuť, vyberte výstup v nastaveniach MIDI.",
  "sequencer-status-open-settings": "Otvoriť nastavenia",
  "sequencer-synth-loading": "Spúšťa sa vstavaný zvuk…",
  "sequencer-status-dismiss": "Zavrieť",
  "sequencer-synth-error": "Vstavaný zvuk sa nespustil:",
  "sequencer-synth-mute": "Stlmiť vstavaný syntetizátor",
  "sequencer-synth-mute-hint":
    "Prepne nastavenie výstupu MIDI do vstavaného syntetizátora",
  "sequencer-soundfont-hint":
    "Zvuky, ktoré hrá vstavaný syntetizátor. Pridajte vlastné súbory SF2, SF3 alebo DLS.",
  "sequencer-soundfont-list": "SoundFonty",
  "sequencer-soundfont-add": "Pridať",
  "sequencer-soundfont-adding": "Pridáva sa…",
  "sequencer-soundfont-remove": "Odstrániť {name}",
  "sequencer-soundfont-by": "Autor: {author}",
  "sequencer-soundfont-loading": "Načítava sa…",
  "sequencer-soundfont-add-error": "Nepodarilo sa ho pridať:",
  "sequencer-error-not-soundfont": "{name} nie je SoundFont",
  "sequencer-error-soundfont-fetch":
    "SoundFont sa nepodarilo stiahnuť ({status})",
  "sequencer-error-soundfont-gone": "Tento SoundFont už nie je uložený",
  "sequencer-soundfont-saved-notice":
    "Pridané SoundFonty sa ukladajú v tomto prehliadači.",
  "sequencer-soundfont-off-hint":
    "Počuť ich, keď je vstavaný syntetizátor vybraný ako výstup na karte MIDI.",
}

export default sk
