import type { Translation } from "./en"

// Simplified Chinese
const zhHans: Translation = {
  "sequencer-preview-pending": "正在准备预览…",
  "sequencer-preview-unavailable": "预览不可用",
  "sequencer-panel": "音序器",
  "sequencer-grid": "网格",
  "sequencer-step-editor": "步编辑器",
  "sequencer-voices": "声部",
  "sequencer-settings-panes": "设置面板",
  "sequencer-action-hold": "保持",
  "sequencer-action-sync": "同步",
  "sequencer-action-flip": "翻转",
  "sequencer-action-transpose": "移调",
  "sequencer-action-hold-hint": "音序器停在当前步，声部继续播放（H）",
  "sequencer-action-sync-hint":
    "让所选声部按音序器的步速播放，每步一个音符（Y）",
  "sequencer-action-flip-hint": "从下一步起互换网格的行与列（F）",
  "sequencer-action-transpose-hint": "按音序器的「移调」设置为新音符移调（T）",
  "sequencer-action-latch-hint":
    "单击即开启动作，再次单击才关闭，而不是仅在按住时生效",
  "sequencer-actions": "动作",
  "sequencer-action-off": "关",
  "sequencer-action-on": "开",
  "sequencer-play": "播放",
  "sequencer-pause": "暂停",
  "sequencer-stop": "停止",
  "sequencer-bpm-value": "{bpm} BPM",
  "sequencer-step-number": "第 {step} 步",
  "sequencer-steps-count": "{count} 步",
  "sequencer-ccs-count": "{count} 个 CC",
  "sequencer-record": "录制",
  "sequencer-file": "文件",
  "sequencer-edit": "编辑",
  "sequencer-file-new": "新建",
  "sequencer-file-open": "打开…",
  "sequencer-file-save": "保存",
  "sequencer-file-save-as": "另存为…",
  "sequencer-file-export-midi": "导出 MIDI…",
  "sequencer-file-import-midi": "导入 MIDI…",
  "sequencer-file-render-audio": "渲染音频…",
  "sequencer-file-recent-patches": "最近的工程",
  "sequencer-file-recent-midi": "最近导入的 MIDI",
  "sequencer-confirm-discard": "此工程有未保存的更改。要放弃这些更改吗？",
  "sequencer-recent-gone": "找不到 {name}。它可能已被移动或删除。",
  "sequencer-failed-open-recent": "无法打开 {name}。",
  "sequencer-failed-open-file": "无法打开文件。",
  "sequencer-failed-read-patch": "无法打开该文件。",
  "sequencer-failed-save-patch": "无法保存工程。",
  "sequencer-failed-export-patterns": "无法导出节奏型。",
  "sequencer-failed-import-patterns": "无法导入节奏型。",
  "sequencer-failed-read-patterns": "无法导入这些节奏型。",
  "sequencer-failed-export-midi": "无法导出 MIDI。",
  "sequencer-failed-export-step": "无法将该步导出为 MIDI。",
  "sequencer-failed-open-midi": "无法打开 MIDI 文件。",
  "sequencer-failed-read-midi": "无法读取 MIDI 文件。",
  "sequencer-failed-read-midi-file": "无法导入该文件。",
  "sequencer-failed-save-audio": "无法保存音频。",
  "sequencer-failed-load-soundfont": "无法加载 SoundFont。",
  "sequencer-failed-render-audio": "无法渲染音频。",
  "sequencer-error-read-denied": "浏览器未获准读取该文件。",
  "sequencer-import-midi": "导入 MIDI：{name}",
  "sequencer-import-action": "导入",
  "sequencer-import-nothing": "此范围内没有可导入的内容",
  "sequencer-import-fills": "填充第 {first}–{last} 步（共 {total} 步）",
  "sequencer-import-round": "循环 {times}×",
  "sequencer-import-dealt": "{steps} 步，每步 {notes} 个音符",
  "sequencer-import-dont-fit": "{count} 个音符超出网格",
  "sequencer-import-preview": "预览：{name}",
  "sequencer-import-loading": "正在读取 {name}…",
  "sequencer-import-filter": "MIDI 过滤",
  "sequencer-import-options": "选项",
  "sequencer-import-tracks-chosen": "已选 {chosen}/{count} 条轨道",
  "sequencer-import-notes-a-step": "每步 {count} 个音符",
  "sequencer-import-from": "从第 {step} 步起",
  "sequencer-import-looping": "循环填充",
  "sequencer-import-filter-hint":
    "初始值取自「设置」中的 MIDI 输入过滤；此处的更改仅对本次导入有效。被过滤掉的音符显示为灰色，不会导入。",
  "sequencer-import-filtered": "已过滤",
  "sequencer-import-all-channels": "所有通道",
  "sequencer-import-no-channels": "无通道",
  "sequencer-import-all-notes": "所有音符",
  "sequencer-import-snap": "吸附",
  "sequencer-import-snap-bar": "小节",
  "sequencer-import-snap-beat": "拍",
  "sequencer-import-snap-off": "关",
  "sequencer-import-start": "导入起点",
  "sequencer-import-end": "导入终点",
  "sequencer-import-bar": "第 {bar} 小节",
  "sequencer-import-parts": "轨道",
  "sequencer-import-no-notes": "此文件没有音符。",
  "sequencer-import-track": "轨道 {track}",
  "sequencer-import-notes": "{count} 个音符",
  "sequencer-import-notes-per-step": "每步音符",
  "sequencer-import-drums": "鼓",
  "sequencer-import-no-ccs": "此文件不含 CC。",
  "sequencer-import-changes": "{count} 次变化",
  "sequencer-import-steps": "步",
  "sequencer-import-size-fit": "适应",
  "sequencer-import-size-fit-hint":
    "调整音序步数，使其在导入填充的最后一步结束",
  "sequencer-import-from-step": "起始步",
  "sequencer-import-loop": "循环直至填满网格",
  "sequencer-import-tempo": "采用文件中的速度",
  "sequencer-import-no-tempo": "文件未指定",
  "sequencer-import-hint":
    "在范围内开始的音符按播放顺序放入各步，每步放入所选的数量（该数量会成为「每步音符」），同一琴键每步只放一次。红色音符超出网格。CC 会变成覆盖每步音符的阶梯包络。被填充的步会失去原有内容；撤销一次即可撤回导入。",
  "sequencer-import-settings-hint":
    "「文件 → 导入 MIDI」的初始设置。每次导入都可以单独更改。",
  "sequencer-import-skip-drums": "排除鼓通道",
  "sequencer-import-skip-drums-note": "通道 10",
  "sequencer-import-ccs-default": "导入文件中的 CC",
  "sequencer-import-snap-setting": "范围吸附到",
  "sequencer-file-export-step-midi": "导出单步 MIDI…",
  "sequencer-export-step-midi": "导出 MIDI：第 {step} 步",
  "sequencer-export-step-hint":
    "编辑器中的当前步，按音序首次到达它时的样子：它播放的音符和 CC，长度为一步。概率和随机规则会重新生成随机结果。",
  "sequencer-export-settings-hint":
    "「文件 → 导出 MIDI」和「导出单步 MIDI」的初始设置，也决定从网格拖出的步包含什么：把一个步拖到桌面、文件夹或 DAW，即可立即按这些设置生成它的 MIDI 文件。列出的是此音序发送的 CC。",
  "sequencer-export-midi": "导出 MIDI",
  "sequencer-export-midi-action": "导出",
  "sequencer-export-cancel": "取消",
  "sequencer-export-voices": "声部",
  "sequencer-export-ccs": "CC",
  "sequencer-export-all-ccs": "全部 CC",
  "sequencer-export-no-ccs": "此音序不发送 CC。",
  "sequencer-export-modulation-ccs": "调制 CC",
  "sequencer-export-modulation-ccs-note": "驱动设置的 CC",
  "sequencer-export-mod": "调制源 {source}",
  "sequencer-export-tracks": "轨道",
  "sequencer-export-layout-perVoice": "每个声部一条轨道",
  "sequencer-export-layout-combined": "全部合并为一条轨道",
  "sequencer-export-voice-off": "未启用",
  "sequencer-export-passes": "遍数",
  "sequencer-export-bars": "{count} 小节",
  "sequencer-export-hint":
    "从头播放的整个音序：每个声部使用各自的通道和乐器，CC 也在各自的通道上。概率和随机规则会重新生成随机结果。",
  "sequencer-render-audio": "渲染音频",
  "sequencer-render-audio-action": "渲染",
  "sequencer-render-hint":
    "从头播放的整个音序，使用内置音源：{font}。概率和随机规则会重新生成随机结果。",
  "sequencer-render-name": "文件名",
  "sequencer-render-format": "格式",
  "sequencer-render-format-wav": "WAV",
  "sequencer-render-format-mp3": "MP3",
  "sequencer-render-sample-rate": "采样率",
  "sequencer-render-bit-depth": "位深度",
  "sequencer-render-bit-depth-16": "16-bit",
  "sequencer-render-bit-depth-24": "24-bit",
  "sequencer-render-bit-depth-32": "32-bit 浮点",
  "sequencer-render-bitrate": "比特率",
  "sequencer-render-channels": "声道",
  "sequencer-render-channels-2": "立体声",
  "sequencer-render-channels-1": "单声道",
  "sequencer-render-tail": "尾音",
  "sequencer-render-tail-note": "最后一步之后留给余音的时长",
  "sequencer-render-normalize": "标准化",
  "sequencer-render-normalize-note": "最高峰值为 −1 dB",
  "sequencer-render-loading": "正在加载 SoundFont…",
  "sequencer-render-measuring": "正在测量电平…",
  "sequencer-render-rendering": "正在渲染…",
  "sequencer-render-saving": "正在保存…",
  "sequencer-render-progress": "渲染进度",
  "sequencer-mod-seqX": "音序 X",
  "sequencer-mod-seqY": "音序 Y",
  "sequencer-mod-phase": "相位",
  "sequencer-mod-actionOr": "动作",
  "sequencer-mod-voice1Random": "声部 1 随机",
  "sequencer-mod-voice2Random": "声部 2 随机",
  "sequencer-mod-voice3Random": "声部 3 随机",
  "sequencer-mod-voice4Random": "声部 4 随机",
  "sequencer-modulation": "调制",
  "sequencer-modulation-of": "调制：{target}",
  "sequencer-modulation-settings": "调制设置：{target}",
  "sequencer-modulation-by": "由 CC {cc} 调制",
  "sequencer-modulation-cc": "CC",
  "sequencer-modulation-cc-of": "{target} 的 CC",
  "sequencer-modulation-from": "起始",
  "sequencer-modulation-to": "结束",
  "sequencer-modulation-values": "{count} 个值",
  "sequencer-modulation-hint":
    "带有此 CC 包络的步在播放时会设定此项；其他步保持该字段自身的值。包络的取值为「起始」到「结束」之间的值。",
  "sequencer-modulation-action-hint":
    "带有此 CC 包络的步会开启或关闭该动作，不论其按钮状态如何：「保持」和「翻转」在该步结束时生效，「同步」在该步开始时生效，「移调」在每个音符上生效。其他步由按钮决定。",
  "sequencer-modulation-taken": "CC {cc}：已用于调制 {target}",
  "sequencer-modulation-on-steps": "CC {cc}：已在 {count} 步上使用",
  "sequencer-modulation-on": "所在步：{steps}",
  "sequencer-modulation-on-none": "不在任何步上",
  "sequencer-modulation-assign": "调制",
  "sequencer-modulation-show": "在第 {step} 步上显示",
  "sequencer-modulation-remove": "移除",
  "sequencer-modulation-remove-hint":
    "停止此 CC 对该项的调制。它的包络会保留为普通 CC。",
  "sequencer-modulation-tab-transpose-fit": "移调适配",
  "sequencer-modulation-tab-sequencer-pace": "音序步速",
  "sequencer-modulation-tab-sequencer-transpose": "音序移调",
  "sequencer-modulation-tab-sequencer-transpose-fit": "录制适配",
  "sequencer-modulation-modulates": "调制对象：{target}",
  "sequencer-undo": "撤销",
  "sequencer-redo": "重做",
  "sequencer-size": "步数",
  "sequencer-pace": "步速",
  "sequencer-direction": "方向",
  "sequencer-direction-fwd": "正向",
  "sequencer-direction-bwd": "反向",
  "sequencer-direction-fwdbwd": "正 / 反",
  "sequencer-direction-bwdfwd": "反 / 正",
  "sequencer-direction-random": "随机",
  "sequencer-direction-random+": "随机+",
  "sequencer-loop": "循环",
  "sequencer-loop-recorded": "已录制",
  "sequencer-loop-all": "全部",
  "sequencer-loop-custom": "自定义",
  "sequencer-loop-end": "循环终点",
  "sequencer-sync-voices": "同步声部",
  "sequencer-transpose-amt": "移调",
  "sequencer-transpose-fit": "音阶适配",
  "sequencer-record-fit": "录制适配",
  "sequencer-max-notes": "每步音符",
  "sequencer-voice": "声部",
  "sequencer-voice-enable": "启用",
  "sequencer-voice-length": "时值",
  "sequencer-voice-rule": "规则",
  "sequencer-rule-nth": "第 N 个",
  "sequencer-rule-lowest": "最低",
  "sequencer-rule-highest": "最高",
  "sequencer-rule-random": "随机",
  "sequencer-rule-up": "上行",
  "sequencer-rule-down": "下行",
  "sequencer-rule-updown": "上下行",
  "sequencer-rule-downup": "下上行",
  "sequencer-rule-updown+": "上下行 +",
  "sequencer-rule-downup+": "下上行 +",
  "sequencer-rule-rise": "上升",
  "sequencer-rule-fall": "下降",
  "sequencer-rule-outsidein": "由外向内",
  "sequencer-rule-insideout": "由内向外",
  "sequencer-rule-ends": "两端",
  "sequencer-rule-shuffle": "乱序",
  "sequencer-rule-walk": "游走",
  "sequencer-rule-norepeat": "不重复",
  "sequencer-voice-velocity": "力度",
  "sequencer-voice-velocity-of": "声部 {voice} 力度",
  "sequencer-voice-channel": "通道",
  "sequencer-voice-instrument": "乐器",
  "sequencer-voice-pattern-length": "节奏型",
  "sequencer-voice-dot": "点",
  "sequencer-voice-dot-of": "声部 {voice} 第 {dot} 点",
  "sequencer-tempo": "速度",
  "sequencer-step-state": "状态",
  "sequencer-step-state-normal": "正常",
  "sequencer-step-state-rest": "休止",
  "sequencer-step-state-skip": "跳过",
  "sequencer-step-note": "音符",
  "sequencer-step-add-note": "添加音符",
  "sequencer-step-remove-note": "移除音符",
  "sequencer-step-remove-note-of": "移除音符 {note}",
  "sequencer-step-no-notes": "没有音符。请录制或添加。",
  "sequencer-step-over-limit": "超出上限的音符会变暗且不发声。",
  "sequencer-step-trim": "裁剪至上限",
  "sequencer-step-out-of-scale": "不在音阶内",
  "sequencer-step-ccs": "力度和 CC",
  "sequencer-step-add-cc": "添加 CC",
  "sequencer-step-more-lanes": "更多栏",
  "sequencer-step-remove-cc": "移除 CC",
  "sequencer-step-remove-cc-modulation": "移除 CC 及其对 {target} 的调制",
  "sequencer-step-cc-values": "CC 值",
  "sequencer-step-cc-copy": "复制值",
  "sequencer-step-cc-paste": "粘贴值",
  "sequencer-step-cc-clear": "清除此步的值",
  "sequencer-velocity-voice-off": "未启用",
  "sequencer-step-cc": "CC",
  "sequencer-channel-short": "通道 {channel}",
  "sequencer-envelope-not-on-step": "此步没有，绘制即可添加",
  "sequencer-envelope": "包络",
  "sequencer-envelope-cc-number": "CC 编号",
  "sequencer-envelope-cc-channel": "CC 通道",
  "sequencer-envelope-edit": "编辑",
  "sequencer-envelope-edit-tool": "编辑节点",
  "sequencer-envelope-draw": "绘制",
  "sequencer-envelope-erase": "擦除",
  "sequencer-envelope-erase-hint": "擦除节点：单击或拖过它们",
  "sequencer-envelope-grid": "网格",
  "sequencer-envelope-point": "节点",
  "sequencer-envelope-point-value": "值",
  "sequencer-envelope-point-value-of": "节点 {point} 的值",
  "sequencer-envelope-point-delete": "删除节点",
  "sequencer-envelope-steps": "阶梯",
  "sequencer-envelope-steps-hint": "阶梯：每个值保持到下一个节点，然后跳变",
  "sequencer-envelope-ramps": "斜坡",
  "sequencer-envelope-ramps-hint": "斜坡：从每个节点以直线连到下一个节点",
  "sequencer-collapse-scale": "折叠音阶——仅显示音序用到的琴键",
  "sequencer-envelope-ruler": "标尺——向上拖动放大，向下拖动缩小，左右拖动滚动",
  "sequencer-action-latch": "锁定",
  "sequencer-preview": "试听步",
  "sequencer-patch-name": "工程名称",
  "sequencer-patch-name-of": "工程名称：{name}",
  "sequencer-patch-rename": "重命名工程",
  "sequencer-jump-rule": "规则",
  "sequencer-jump-dest": "目标",
  "sequencer-jump-normal": "常规",
  "sequencer-jump-pick-dest": "选择目标",
  "sequencer-jump-pick-normal": "选择常规步",
  "sequencer-jump-add": "跳转规则",
  "sequencer-jump-remove": "移除跳转",
  "sequencer-jump-none": "无",
  "sequencer-jump-next": "下一步",
  "sequencer-jump-always": "始终",
  "sequencer-jump-last": "上次通过",
  "sequencer-jump-not-last": "上次未通过",
  "sequencer-jump-hint": "在网格中单击一个步来设置。",
  "sequencer-dot-collision": "与其他声部音符相同：{note} · 声部 {voices}",
  "sequencer-dot-hint": "右键单击点可打开其步选项。",
  "sequencer-voice-patterns": "节奏型",
  "sequencer-voice-pattern": "声部 {voice} 节奏型",
  "sequencer-voice-select": "选择声部 {voice}",
  "sequencer-voice-mute": "静音",
  "sequencer-voice-mute-of": "静音声部 {voice}",
  "sequencer-voice-solo": "独奏",
  "sequencer-voice-solo-of": "独奏声部 {voice}",
  "sequencer-patterns-export": "导出节奏型",
  "sequencer-patterns-import": "导入节奏型",
  "sequencer-dot-articulation": "奏法",
  "sequencer-dot-articulation-none": "无",
  "sequencer-dot-articulation-hold": "保持",
  "sequencer-dot-articulation-tie": "连音",
  "sequencer-dot-accent": "重音",
  "sequencer-dot-ratchet": "棘轮",
  "sequencer-dot-probability": "概率",
  "sequencer-dot-condition": "条件",
  "sequencer-dot-none": "无",
  "sequencer-dot-always": "始终",
  "sequencer-dot-last": "同前",
  "sequencer-dot-not-last": "反前",
  "sequencer-dot-condition-always-hint": "始终：节奏型每次到达此点时都播放",
  "sequencer-dot-condition-2:2-hint":
    "2:2：第 1 次循环不发声，每两次循环中的第 2 次播放（第 2、4、6… 次）",
  "sequencer-dot-condition-3:3-hint":
    "3:3：第 1、2 次循环不发声，每三次循环中的第 3 次播放（第 3、6、9… 次）",
  "sequencer-dot-condition-4:4-hint":
    "4:4：第 1–3 次循环不发声，每四次循环中的第 4 次播放（第 4、8、12… 次）",
  "sequencer-dot-condition-1x-hint":
    "1x：播放一次循环，跳过下一次，依此类推（第 1、3、5… 次）",
  "sequencer-dot-condition-2x-hint":
    "2x：连续播放两次循环，然后跳过第三次（第 1、2、4、5… 次）",
  "sequencer-dot-condition-3x-hint":
    "3x：连续播放三次循环，然后跳过第四次（第 1、2、3、5… 次）",
  "sequencer-dot-condition-last-hint":
    "同前：仅当紧邻的前一个点播放时才播放；若前一个点未通过概率、被条件跳过或处于关闭状态，则不播放",
  "sequencer-dot-condition-notLast-hint":
    "反前：仅当紧邻的前一个点未播放时才播放，可在前一个点未通过概率或条件时作为替补",
  "sequencer-dot-reset": "重置点",
  "sequencer-dot-copy": "复制",
  "sequencer-dot-paste": "粘贴",
  "sequencer-dot-shift-left": "左移",
  "sequencer-dot-shift-right": "右移",
  "sequencer-dot-swap-left": "与左交换",
  "sequencer-dot-swap-right": "与右交换",
  "sequencer-dot-insert-before": "在前插入",
  "sequencer-dot-insert-after": "在后插入",
  "sequencer-step-copy": "复制",
  "sequencer-step-paste": "粘贴",
  "sequencer-step-clear": "清除",
  "sequencer-step-insert-before": "在前插入",
  "sequencer-step-insert-after": "在后插入",
  "sequencer-step-delete": "删除",
  "sequencer-scale": "音阶",
  "sequencer-scale-tonic": "音阶主音",
  "sequencer-scale-none": "半音阶",
  "sequencer-scale-common": "常用",
  "sequencer-scale-more": "更多",
  "sequencer-scale-fit": "音阶外音符",
  "sequencer-scale-fit-up": "上移",
  "sequencer-scale-fit-down": "下移",
  "sequencer-scale-fit-exclude": "排除",
  "sequencer-scale-fit-ignore": "原样",
  "sequencer-scale-detected": "检测到",
  "sequencer-scale-no-notes": "没有可供检测的音符",
  "sequencer-scale-detect": "检测音阶",
  "sequencer-scale-chromatic": "半音阶",
  "sequencer-scale-moved": "已移动 {count} 个",
  "sequencer-scale-left-out": "已排除 {count} 个",
  "sequencer-import-scale-hint":
    "根据所选范围内的音符检测得出。音阶外的音符可上移或下移以适配音阶、排除，或保持原样。",
  "sequencer-import-min-velocity": "最小力度",
  "sequencer-import-min-velocity-note": "力度更低的音符会被排除",
  "sequencer-import-quiet": "{count} 个音符力度过低",
  "sequencer-import-note-low": "最低音",
  "sequencer-import-note-high": "最高音",
  "sequencer-import-all-parts": "全选",
  "sequencer-import-no-parts": "全不选",
  "sequencer-settings": "设置",
  "sequencer-settings-general": "常规",
  "sequencer-settings-theme": "主题",
  "sequencer-settings-midi": "MIDI",
  "sequencer-settings-soundfont": "SoundFont",
  "sequencer-settings-export": "MIDI 导出",
  "sequencer-settings-import": "MIDI 导入",
  "sequencer-settings-close": "关闭",
  "sequencer-language": "语言",
  "sequencer-accent-amount": "重音幅度",
  "sequencer-accent-amount-hint": "重音使音符力度升高或降低的幅度。",
  "sequencer-theme-mode": "模式",
  "sequencer-theme-mode-light": "浅色",
  "sequencer-theme-mode-dark": "深色",
  "sequencer-theme-mode-system": "跟随系统",
  "sequencer-theme-system-hint": "跟随电脑的浅色或深色设置。",
  "sequencer-theme-dark-theme": "深色主题",
  "sequencer-theme-light-theme": "浅色主题",
  "sequencer-theme-default": "默认",
  "sequencer-midi-inputs-section": "输入",
  "sequencer-midi-voice-outputs": "声部输出",
  "sequencer-midi-voice-outputs-hint":
    "声部还可以发送到自己的专属端口，与上方的端口同时输出。",
  "sequencer-midi-send-modulation-ccs": "发送调制 CC",
  "sequencer-midi-modulation-ccs-hint":
    "驱动调制设置的 CC 会像其他步 CC 一样发送到每个已勾选的输出。关闭时，它们仅用于驱动设置。",
  "sequencer-clock": "时钟",
  "sequencer-clock-send": "发送 MIDI 时钟",
  "sequencer-clock-hint":
    "开始、停止消息以及每拍 24 个时钟脉冲会发送到每个已勾选的输出，让所有接收端跟随 midiseq 的速度。",
  "sequencer-clock-follow": "跟随 MIDI 时钟速度",
  "sequencer-clock-follow-hint":
    "已勾选的输入收到的时钟会设定速度。开始和停止消息会被忽略，播放和停止仍由你控制。",
  "sequencer-filter": "输入过滤",
  "sequencer-filter-hint": "已勾选的输入允许传入哪些内容。",
  "sequencer-filter-channels": "通道",
  "sequencer-filter-none": "全不选",
  "sequencer-filter-all": "全选",
  "sequencer-filter-range": "音符范围",
  "sequencer-filter-low": "最低音",
  "sequencer-filter-high": "最高音",
  "sequencer-filter-to": "至",
  "sequencer-filter-transpose": "移调",
  "sequencer-filter-semitones": "半音",
  "sequencer-filter-ccs": "CC 过滤",
  "sequencer-midi-outputs-section": "输出",
  "sequencer-midi-channel": "通道",
  "sequencer-midi-no-inputs":
    "未找到 MIDI 输入。请连接键盘，或使用 loopMIDI 端口。",
  "sequencer-output-voice": "声部",
  "sequencer-output-none": "无",
  "sequencer-output-disconnected": "{name}（已断开）",
  "sequencer-builtin-synth": "内置合成器",
  "sequencer-midi-unsupported":
    "此浏览器不支持 Web MIDI。请使用 Chrome、Edge、Opera 或 Firefox。",
  "sequencer-midi-unsupported-toast":
    "此浏览器不支持 Web MIDI，无法连接你的 MIDI 设备。内置合成器仍可播放。",
  "sequencer-midi-unsupported-browsers": "支持的浏览器",
  "sequencer-midi-error": "无法访问 MIDI：",
  "sequencer-midi-permission-hint":
    "浏览器阻止了 MIDI。请在此网站的设置中允许 MIDI 设备（地址栏左侧的图标），然后重试。",
  "sequencer-midi-retry": "重试",
  "sequencer-midi-enable": "启用 MIDI",
  "sequencer-midi-enable-hint": "midiseq 需要你的许可才能使用 MIDI 设备。",
  "sequencer-no-input": "没有可录制的输入。请在「设置」中勾选一个 MIDI 输入。",
  "sequencer-no-output":
    "尚未路由到任何输出。请在 MIDI 设置中选择一个输出才能听到声音。",
  "sequencer-status-open-settings": "打开设置",
  "sequencer-synth-loading": "正在启动内置音源…",
  "sequencer-status-dismiss": "关闭",
  "sequencer-synth-error": "内置音源未能启动：",
  "sequencer-synth-mute": "将内置合成器静音",
  "sequencer-synth-mute-hint": "切换内置合成器的 MIDI 输出设置",
  "sequencer-soundfont-hint":
    "内置合成器所用的音色。可添加你自己的 SF2、SF3 或 DLS 文件。",
  "sequencer-soundfont-list": "SoundFont",
  "sequencer-soundfont-add": "添加",
  "sequencer-soundfont-adding": "正在添加…",
  "sequencer-soundfont-remove": "移除 {name}",
  "sequencer-soundfont-by": "作者：{author}",
  "sequencer-soundfont-loading": "正在加载…",
  "sequencer-soundfont-add-error": "无法添加：",
  "sequencer-error-not-soundfont": "{name} 不是 SoundFont",
  "sequencer-error-soundfont-fetch": "无法获取 SoundFont（{status}）",
  "sequencer-error-soundfont-gone": "该 SoundFont 已不再保存",
  "sequencer-soundfont-saved-notice": "添加的 SoundFont 会保存在此浏览器中。",
  "sequencer-soundfont-off-hint":
    "在「MIDI」中将内置合成器选为输出后即可听到。",
}

export default zhHans
